= Angus' Spirit Almanach

A collection of the spirit-world knowledge of [Angus
Swims-under-Ice](Angus "wikilink"). Certainly incomplete and subject to
constant change, as usual for the spirit world. An overview is provided
on the [Spirits](Spirits "wikilink") page.

Note: Opposed to other parts on this wiki, some (perhaps even most) of
the articles in this category are character-knowledge and may be
inaccurate or even plain wrong.

== Athumu

High ranking sewer spirit with an associated court, most likely part of
the [water spirits](Die_Flüssigen "wikilink"). Was disposed by the
[Great Slimy One](Great_Slimy_One "wikilink") using a weapon, a ridden,
that was delivered to him by the pack.

== Blood of the city

A powerful [spirit court](spirits "wikilink") concerned with everything
that keeps a city "running" - trade, traffic, electricity ... the list
is long, and many spirits belong to this court. The court is not young,
probably reaching back to the first cities, but it has changed a lot
over time and certainly grown more powerful in the modern world, where
cities have surged in importance.

Blood of the City has very weird internal rules and structures. It seems
the court is organised in "boards" (which might mean brood or not), who
cover certain areas of activity. There also exists some strange feudal
structure, perhaps a relict of older days, that is based on the transfer
of essence: Paying essence to a spirit makes him your liege. A liege is
supposed to speak on all matters that concern his vassals, but this
vassals may still speak on matters that concern others, for example
their own vassals. It is not unheard of for circles of allegiance to
form (A is lord of B is lord of C is lord of A). All this, and the fact
that Blood of the City can be quite unified if there is a threat, makes
the court difficult and trying to deal with.

[The Director](The_Director "wikilink") is a Jaggling member the players
have dealt with.

== Cat spirits

The [pack](pack "wikilink") has friendly ties towards cat spirits, a
part of the [Urban Ronins](Urban_Ronins "wikilink"), not only because
the [totem](totem "wikilink") is a cat spirit. The pack also protects
the cats in the sewer mazes from attacks of the dog spirits. In
exchange, the cats act as information gatherers and disseminaters.

== Cinema Spirit

The spirit of the local [cinema](Spartak_cinema "wikilink"), of assumed
Jaggling rank. The pack has had some fairly reasonable contacts with it.
The spirit helped the pack create a large amount of darkness essence, to
lure and ultimately kill a darkness spirit. Recently, the pack has
learned of the theatre spirits from the Cinema Spirit. Angus is
re-viving a [cinema club](cinema_club "wikilink") as part of the
payment.

== Concrete wood

Concrete wood is a [spirit court](spirits "wikilink") encompassing the
"bones" of the city: buildings, streets, channels, etc. As in real life
and as the trees in a wood, the court is omnipresent (and quite vital to
the existence of the city's Hisil denisens), but not very active or
powerful. Most spirits are greater Gafflings, but they are totally fixed
on their sorroundings, ignorant to the going-ons outside their houses.

The court seems organised in "neighbourhoods", which encompass all
members in a certain area and are supposed to be able to communicate
(painfully slowly). Most buildings of importance have spirits that leave
this court to join a more active one; therefore there are almost no
Jaggling members.

== Court of Eternal Grace

A [spirit court](spirits "wikilink") concerned with the arts, culture
and associated things. It is unclear how far exactly the domain of this
court goes, but given that it is quite powerful and many of the old
historical buildings also belong to it, it might even encompass nobility
and similar cnocepts. The pack came into contact with the court during
the events of [the old werewolf's last
play](the_old_werewolf's_last_play "wikilink"). Possibly, [Prince
Yaromir](Prince_Yaromir "wikilink") is a member of this court. Other
likely members include the spirit known as [Meister im
Norden](Meister_im_Norden "wikilink") and [the Bleeding
Stone](the_Bleeding_Stone "wikilink").
[Kaffeehaus](Kaffeehaus "wikilink"), the spirit of [Café
Alexanderplatz](Café_Alexanderplatz "wikilink"), is a member of this
court allied with the pack.

The court has a mixed history with the pack, acting as opponent during
[the old werewolf's last play](the_old_werewolf's_last_play "wikilink"),
as advisors during [the fate of The Bleeding
Stone](the_fate_of_The_Bleeding_Stone "wikilink") and recently as an
ally during the events at [Petersburg
Wilhelmplatz](Petersburg_Wilhelmplatz "wikilink"), then using them in
[reality theatre](reality_theatre "wikilink").

The pack has learned that the Jaggling members of this court tend to
build domains for themselves in retreats in the Shadow, places that have
no direct physical reflection, and rarely leave them. Interestingly, the
broods of those Jagglings often contain members of other courts.
Politics seem to be on an individual basis with the Jaggling members.

It is assumed that all Jaggling members of this court are also members
of [the High Court of
Petersburg](the_High_Court_of_Petersburg "wikilink"). The court has an
old alliance to the [Urban Ronins](Urban_Ronins "wikilink"), but is in
conflict with the new stronger courts, [Fleshmade](Fleshmade "wikilink")
and [Blood of the City](Blood_of_the_City "wikilink").

The [Steel Predators](Steel_Predators "wikilink") have an old feud with
this court, something about a broken deal a century ago.

== Daemonium

A spirit of St. Petersburg, suffering and violence. It embodies the
aspect of the city as a place built on the blood of innocents, a
battlefield, and the centre of an emerging military power. It seems to
have once been allied to the Pure, but since the reconquest of the city
by the Forsaken no werewolf has seen it.

== Die Flüssigen

A large spirit court encompassing all spirits that deal with water in
all its forms -- rain, rivers, probably even tears and sweat, though
only in a very minor way.

== EepEeps

Information spirits friendly to the pack. They call the pack's main
[locus](Old_radio "wikilink") their home and have made a deal with the
pack encompassing the following points:

  - The pack will protect the EepEeps from other spirits.
  - The pack owns the locus, giving them free access anytime they want.
  - The EepEeps are entitled to half the essence generated by the locus.
    They inform the pack if there is trouble on their side of the locus.

== Eternal Grace

A name applying to two highly ranked members of the [court of Eternal
Grace](court_of_Eternal_Grace "wikilink"): [Prince
Yaromir](Prince_Yaromir "wikilink") and [the
maiden](the_maiden "wikilink"). Why exactly that is and if there is any
sensible reason remains to be seen.

== Fleshmade

Fleshmade is a [spirit court](Spirits "wikilink") nominally encompassing
all items made by mankind. Since the court is quite new (it emerged
during the final phases of industrialisation with the advent of mass
production), this claim is quite far from reality: Everything that
already existed belonged to other courts (mainly [Blood of the
City](Blood_of_the_City "wikilink") and [Court of Eternal
Grace](Court_of_Eternal_Grace "wikilink")). Thus the court started in a
niche, encompassing the "soulless" mass-produced items. These have
become very common, though, and so the Court has grown in power and
seems to be among the top players today. It is still easy not to notice
it, though.

Today, the spirits of the court usually belong to items that are
considered to lack 'identity' (everything humans usually don't have a
personal connection to), and associated conceptual spirits. Due to its
(relatively) fast rise to power and conflicting claims, the court has
many enemies, especially among the more powerful courts.

The pack has found the spirit of the pharmacy at
[Wilhelmplatz](Wilhelmplatz "wikilink") hiding as a Ridden. They gave it
to [Blood of the City](Blood_of_the_City "wikilink") to gain favour with
the court.

== Giftläufer

Spirits in the service of the [Great Slimy
One](Great_Slimy_One "wikilink"). Their ban is known: a specific weed
that makes them wary to attack.

== Great Slimy One

The 'Great Slimy One' was a lesser Jaggling that manifested in the
sewers due to the biological waste [transported there by some criminal
elements](fight_in_the_sewers "wikilink"). It quickly took over the main
locus in the sewers (situated right on the origin of the contamination),
replacing [Athumu](Athumu "wikilink"), and established its own court. In
the following weeks, the court grew stronger and stronger, until it was
the predominant court throughout most of the sewers.

The [Giftläufer](Giftläufer "wikilink") were a kind of spirit that
provided muscle for his court, and an enemy the pack repeatedly faced.

He was eventually discorporated by the pack and subsequently destroyed
during the [cleansing of its locus](fight_in_the_sewers "wikilink").

== Grey Court

A powerful yet fractured spirit court. It is related to negative
emotions, but not to violent ones - gloom, despair and fear seem to be
most prevalent. It is likely the most powerful court in the pack's
territory, but it has almost no unity - there are some more powerful
spirits in this court who are in fierce competition for followers.
Prominent members include
[She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink") and
[Pitch Black](Pitch_Black "wikilink").

Another powerful member was the previous owner of the pack's
[locus](old_radio "wikilink"), but it was destroyed by the pack.

== Großer Sirocool

A spirit of a great hacker. Believed to be of Jaggling rank, very
possibly Greater Jaggling. Might be part of the
[Network](Network "wikilink") court.

== Handmaidens of Bloodshed

A spirit court of mercenaries, who sell their services for essence.
Known appearances are crouched,black figures with shotguns or
knives/swords as arms.

== Kaffeehaus

The [spirit](spirits "wikilink") of [Café
Alexanderplatz](Café_Alexanderplatz "wikilink"), a member of the [Court
of Eternal Grace](Court_of_Eternal_Grace "wikilink"). It previously was
the spirit of another café that became collateral damage during [the
fate of The Bleeding Stone](the_fate_of_The_Bleeding_Stone "wikilink").
The [pack](Shadowclaws "wikilink") has convinced it to try and remove
the barren; they have gathered and coerced spirits for its brood or for
consumption and provided essence and security, both themselves and via a
deal with [Blood of the City](Blood_of_the_City "wikilink").

Kaffeehaus is of greater Gaffling rank, probably of medium power among
greater Gafflings.

== Legion

Legion is a [spirit court](Spirits "wikilink") consisting of insects,
invertebrae and associated concepts. It is easily overseen and likely
not very powerful. Spirits of insects that work in groups or swarms can
sometimes be found - they consist of hundreds of animals and move with a
characteristic noise. For solitary insects, only rumours exist.

The pack has met one cockroach spirit during the events at [Petersburg
Wilhelmplatz](Petersburg_Wilhelmplatz "wikilink"), but had no other
contact with the court so far.

== Meister im Norden

Enigmatic and mostly unknown high-ranking spirit in the
[sewers](sewers "wikilink"). Is believed to be a spirit of the times of
old, smuggling and taking no orders.

== Network

A spirit court. Not much is known of these, but the
[EepEep](EepEep "wikilink") are part of them, as likely is [Großer
Sirocool](Großer_Sirocool "wikilink").

== Nevskys Sword

Nevskys Sword is a [Steel Predator](Steel_Predators "wikilink"), the
[spirit](spirits "wikilink") of the [Alexander Nevsky
Bridge](http://en.wikipedia.org/wiki/Alexander_Nevsky_Bridge) located at
the eastern border of the no-mans-land, bordering the
[Glasfelle](Glasfelle "wikilink") territory and close to the [Crimson
Tears](Crimson_Tears "wikilink"). Still, its influence stretches right
to the current eastern border of the
[Shadowclaws](Shadowclaws "wikilink").

The spirit is very powerful, its name evokes a certain awe in the Hisil
of Petersburg. According to [Andrei
Wind-in-den-Straßen](Andrei_Wind-in-den-Straßen "wikilink"), it is of
Greater Jaggling rank and he and his pack go to a certain length to
prevent provocating it. He says the name is from a famous quote of the
russian hero Alexander Nevsky, namesake of the bridge: "He who comes to
us with a sword, from a sword will perish.". The bridge feeds on all
passing spirits, and it has a number of "spirit packs" at its service
that drive or lure prey to the bridge, feeding on the scraps left by the
powerful Jaggling.

== Pitch Black

Pitch Black is a spirit of the [Grey Court](Grey_Court "wikilink"), a
rival of
[She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink").
Little is known about him, but he must be of Jaggling Rank.

== Prince of the River

A very high-ranking spirit, of at least Jaggling rank, quite possibly
higher. He most likely belongs the court of [water
spirits](Die_Flüssigen "wikilink") The pack owes him four favours, of
unspecified duration and level of danger. For these favours, the Prince
helped the pack with the rite to cleanse the [Great Slimy
One's](Great_Slimy_One "wikilink") locus, providing five lesser
Gafflings that would be destroyed in the process. The bargaining only
implied that these favours have to at least theoretically be possible
for the pack to achieve.

One of the five favours was [called
in](The_fate_of_The_Bleeding_Stone "wikilink") recently, giving the pack
the opportunity to get free of all of them - which they chose not to do.

== Prince Yaromir

A spirit of a [now-destroyed
theatre](garbage-burning_facility "wikilink") of at Greater Jaggling
rank. It seems Prince Yaromir is a spirit of acting and theater in
general, a fact he [impressively displayed](reality_theatre "wikilink")
by manipulating the werewolves of Petersburg so they unwittingly
participated in a play designed to strengthen his
[court](Court_of_Eternal_Grace "wikilink").

Probably not coincidently, this is also the name of the male main
character of a famous (in Russia, that is) russian theatre play, based
on an old tale.

Strangely, another name this spirit goes by is [Eternal
Grace](Eternal_Grace "wikilink") - a name shared by another Greater
Jaggling of his court, [the maiden](the_maiden "wikilink").

== Rahglu

A strange breed of spirit and flesh, the Rhaglu appear as sheep-sized
wasps. Little is known about them, and it took Angus days to find their
name even with help of the [Enlightened](Enlightened "wikilink"). The
few facts that are known are:

  - They are not Spirits (at least not fully). The Ithalunim did not
    even know the names of them.
  - They seem to posses strength in numbers. A lone Rhaglu is weak, but
    when the [pack](Shadowclaws "wikilink") was
    [ambushed](Breeding_Grounds "wikilink") by 7 of them it was almost
    wiped out.
  - They have a hive-like structure, as there are many underneath [St.
    Nicholaus Cathedral](St._Nicholaus_Cathedral "wikilink"). At least 3
    types exist: Simple 'workers' wo make up the majority, fierce
    warriors wo seem primarily concerned with protecting the nest, and
    queens which probably function as some sort of hive mind, as she is
    not needed for laying eggs.
  - They procreate by laying eggs into humans, which then hatch within
    about a month, consuming their hosts. They favour wolfblooded since
    these have a higher-than-average stamina, allowing for more eggs to
    successfully hatch. All workers can lay eggs, not only the queen.
  - They have a basic understanding of human society, hiding their
    victims and acting as to not draw too much attention.
  - They seem to communicate based on scent, and supernaturally strong
    odours are known to disrupt their unity, making them far easier to
    battle.

== Rote Hof

A spirit court in the sewers. Encompasses discordance, warriors,
violence, lust, torture, knives, pain (rags as a sign of pain),
perverts. Situated at the Abyss. One known Spirit was [Schleier des
Vergessens](Schleier_des_Vergessens "wikilink"), who fled and whose
whereabouts are unknown.

== Schleier des Vergessens

A spirit of the [Roter Hof](Roter_Hof "wikilink"), escaped during the
pack's watch of the access to the Abyss.

== She Who Was Eternally Lost

A spirit of lesser Jaggling rank, also known as "lost Daughter". She
embodies the concepts of mourning and fear of losing someone/something.
She often appears as a large foetus in red clothes. Her first concept
was the spirits of the aborted children of prostitutes, hence her
appearance. Originally she was part of the [Red
Choir](Red_Choir "wikilink"), but she escaped during the events of the
[fight in the sewers](fight_in_the_sewers "wikilink"). There currently
seems to be some infighting in [her court](Grey_Court "wikilink").

The pack (or rather [Aleksandr](Aleksandr "wikilink") bargaining
generously on the pack's behalf) made a deal with it, to save
[Ivana](Ivana "wikilink")'s life. The deal is valid as long as Ivana
lives, so the pack has a safe way out should the need arise. Aleksandr
would probably oppose it, but [Angus](Angus "wikilink") seems quite
willing to use this threat at least as a bargaining chip.

The deal compromises the following points:

  - Both parties will refrain from any path of action that could lead to
    direct attacks on the other parties. This is basically a
    non-aggression treaty with the added security of not being allowed
    to use third parties against one another.
  - The pack will be allowed to use her main
    [locus](Black_locus "wikilink") to cross the Gauntlet, and the
    Werewolves are entitled to a third of the essence generated by the
    locus.
  - In return, the werewolves are bound by oath to help defend the locus
    in rough times, to fight their common enemies from the [Grey
    Court](Grey_Court "wikilink") and to assist her in tracking down
    spirits of her retinue that go rogue.

[Recently](Breeding_Grounds "wikilink"), the spirit has acquired another
[locus](old_altar "wikilink"), and gained control from the
[Rahglu](Rahglu "wikilink"). She-Who-Was–Eternally-Lost is now a name
that is not spoken lightly in the Hisil of the pack's territory.

== Spirits of Fire and Steel

A spirit court situated at the [steel
works](Drnaya_Steel_Works "wikilink") in the pack's territory. The court
is large and very powerful, but stay within their borders (at least
while the pack stays out of theirs). They do not allow access to the
court's territory and are believed to kill on sight. They are known to
have at least one [locus in the
steelworks](locus_in_the_steelworks "wikilink").

Also semi part of this court is the locus in the pack's territory, in
[Angus](Angus "wikilink")' living area. A [locus of Hearth and
Homeliness](Heimeligkeitsfenster "wikilink"), where hobos meet and can
warm themselves. Due to the dual nature of home, fire and buildings,
this is future battleground. The pack has secured right of passage in
the Hearth locus.

== Spirits of Order

A spirit court, known to encompass the police. Allied with the
[Network](Network "wikilink").

== Steel Predators

Spirits normally encompassing cars and trucks. Steel Predators have a
territory where they feed on prey. They are usually lone spirits. The
[pack](pack "wikilink") had dealings with a Jaggling spirit
*[T-34](T-34 "wikilink")*, and the [Steel
Spider](Steel_Spider "wikilink").

== Steel Spider

A spirit whose help was enlisted to fight against the [Great Slimy
One](Great_Slimy_One "wikilink"). Has since this fight risen to Jaggling
rank.

The spirit was part of the "Geschaffenen" or possibly "Beständigen"
court, and quite Independent. It has changed allegiance to the [Steel
Predators](Steel_Predators "wikilink") during the events sorrounding
[the fate of The Bleeding
Stone](the_fate_of_The_Bleeding_Stone "wikilink"), allowing it to escape
a deal with the [Court of Eternal
Grace](Court_of_Eternal_Grace "wikilink") which bound it to servitude.

It is now bound to a sewage cleaning vehicle employed by the [St
Petersburg Sewage and Waste
Authority](St_Petersburg_Sewage_and_Waste_Authority "wikilink"). It
preys on anything smaller than itself in the Sewers, and claims them as
its hunting ground, actively resisting other Steel Predators that would
try to occupy it.

== T-34

The spirit of a large truck, preying on smaller vehicles, stray animals,
and pedestrians. It is not known for its Finesse. A member of the [Steel
Predators](Steel_Predators "wikilink").

T-34 is a lone spirit, claiming a territory encompassing that of the
Shadowclaws, stopping outside the [Drnaya Steel
Works](Drnaya_Steel_Works "wikilink").

== The Bleeding Stone

A Jaggling in the pack's territory. Associated with one of two legends:

((will follow))

== The Director

A Jaggling member of [Blood of the City](Blood_of_the_City "wikilink"),
the pack had dealings with him twice, both times to lend larger amounts
of essence they couldn't find themselves. He usually negotiates via a
Gaffling member of his Court and doesn't show up "in person".

== The High Court of St Petersburg

It seems there is a court of spirits of Jaggling Rank, meeting at the
[Palace Square](Palace_Square "wikilink") on nights where the moon is
split. This court can issue decisions on its members, known as a trial
by peers. The spirits seem to adhere by this decisions.

Werewolves - those that are of Jaggling rank - avoid the court. This is
due to the fact that any participator is deemed a member, and therefore
also subject to rulings of the court. No sane Forsaken wants to submit
himself to the rulings of a bunch of Jagglings.

The [pack](Shadowclaws "wikilink")
[once](The_fate_of_The_Bleeding_Stone "wikilink") persuaded a number of
members of the court to jugde a [spirit](The_Bleeding_Stone "wikilink")
for them. None of them has been to the court, and none has the rank
required.

== The Maiden

The maiden is a greater Jaggling of pure beauty - a very rare breed of
spirit associated with truth, purity and beauty. Her mere presence seems
to have a strong impact on spirits of negative emotions, and it appears
she has Numina capable of freeing a werewolf from the grip of Kuruth.

Spirits of positive emotions or concepts are rather rare in the Hisil of
the World of Darkness, and usually have a slim chance of existing for
any prolonged period. There are just to many spirits of opposing
concepts that ruthlessly hunt and destroy them. Finding even a lesser
Jaggling from those ranks is no easy task, so she is probably the only
greater Jaggling of her choir in western (or even all of) russia.

The maiden belongs to the [court of Eternal
Grace](court_of_Eternal_Grace "wikilink") and is hidden in a complicated
web of pockets in the Hisil of the [Twin
Palaces](Twin_Palaces "wikilink"). It appears her combat capabilities
are rather weak for a greater Jaggling.

She was recently involved in a [play](reality_theatre "wikilink") staged
by [Prince Yaromir](Prince_Yaromir "wikilink"), another Jaggling of her
court, designed to bring [the Bleeding
Stone](the_Bleeding_Stone "wikilink") over to the court. Strangely
enough, [Angus](Angus "wikilink") learned that another name for her
might be [Eternal Grace](Eternal_Grace "wikilink"), a name that also
applies to [Prince Yaromir](Prince_Yaromir "wikilink").

== The Son and the Nephew

Two very weird [spirits](spirits "wikilink") that are reflections of a
riot at [Wilhelmplatz](Wilhelmplatz "wikilink") some 150 years ago. They
appear in the weeks preceding the anniversary of the riot and start
recruiting local spirits to their cause. How exactly this recruitment
works is unclear, but it is on a subconscious basis and even affects
werewolves. Recruits feel a strong urge to fight for their master, and
are usually motivated by a promise of essence and feeding opportunities.
The two parties clash on the date at Wilhelmplatz, were many spirits are
discorporated and the area is drained of essence. This has led to the
formation of a Barren.

The followers of Son and Nephew consist entirely of Gafflings - it is
unclear if this is due to the fact that Jagglings can feel the influence
and leave the area beforehand or if they are immune. Still, the entire
area is split among their followers and the widespread destruction will
not spare anyone who declares no allegiance to either.

Following [recent events](Petersburg_Wilhelmplatz "wikilink"), the
combat between the two spirits has been ritualised, the pack providing a
combatant and the price (a greater Gaffling). As such, the growth of the
Barren has been stopped, yet there is still a spiritual wasteland that
will take much effort to remove ... and it remains to be seen what
becomes of the two spirits.

== Urban Ronins

A [court](spirits "wikilink") consisting of the spirits of larger
animals (mainly cats, birds, dogs) that live in the city. The spirits
are usually quite solitary (even the dogs) and quite paranoid. It is
rumoured they will not accept gifts of essence, a behaviour stemming
from a number of attempts by the city's population to kill their
physical counterparts by laying out poisoned food.

The pack has good connections in particular to the [Cat
Spirits](Cat_Spirits "wikilink"), since their [totem](totem "wikilink")
comes from this brood. The dogs are therefore natural opponents, while
most birds seem content to ignore them.

This court has traditionally good ties with the [Court of Eternal
Grace](Court_of_Eternal_Grace "wikilink") -- a rare thing in the spirit
world.

== Violent Ones

The Violent Ones are a court composed of spirits of - how else could it
be - violence and violent feelings. They are quite strong, yet due to
their nature they are not very united. They are very aggressive, and
usually cannot be bargained with. It is not clear if this is the same
court as the [Roter Hof](Roter_Hof "wikilink") or another one. It seems,
though, that the latter is restricted to the area below [Bar
Strocic](Bar_Strocic "wikilink").

== Window to the West

A spirit of St. Petersburg, lore, and learning. Embodies the aspecet of
the city as a window towards a more enlightened world, and as a place of
progress. It is the patron totem of the
[Enlightened](Enlightened "wikilink"), but has only a very small court
after more than a century of persecution by the Pure.

== Wissendes Auge der Nacht

Wissendes Auge der Nacht is a stray cat spirit encountered by the pack
during their rite of initiation. After the spirit repeatedly stole
essence from an area the pack was guarding, they tracked it down and
gave it a simple choice: Become our totem or perish.

Wissendes Auge der Nacht does not trust easily - as is reflected in its
ban. The initial relationship with the pack was quite strained, given
the blunders the newly changed werewolves made during their first
dealings with the spirit wild. However, as they worked toward securing
their territory, the spirit became a valuable ally, particularly in
their struggle against the [Great Slimy
One](Great_Slimy_One "wikilink").

The Chorus Numina allows Wissendes Auge der Nacht to call upon other
[cat spirits](Cat_Spirits "wikilink") in the territory.

## Stats

**Attributes:** Power 2, Finesse 4, Resistance 3
**Willpower:** 5
**Essence:** 15
**Initiative:** 7
**Defence:** 4
**Speed:** 13
**Size:** 2
**Corpus:** 5
**Influences:** Cats 1, Shadows 1
**Numina:** Material Vision, Chorus
**Bonuses:** Brawl +1 (given); Stealth +2 (pack); Occult +2 (story)
**Ban:** the pack may only eat meat hunted by themselves
