=== Blood of the city

A powerful [spirit court](spirits "wikilink") concerned with everything
that keeps a city "running" - trade, traffic, electricity ... the list
is long, and many spirits belong to this court. The court is not young,
probably reaching back to the first cities, but it has changed a lot
over time and certainly grown more powerful in the modern world, where
cities have surged in importance.

Blood of the City has very weird internal rules and structures. It seems
the court is organised in "boards" (which might mean brood or not), who
cover certain areas of activity. There also exists some strange feudal
structure, perhaps a relict of older days, that is based on the transfer
of essence: Paying essence to a spirit makes him your liege. A liege is
supposed to speak on all matters that concern his vassals, but this
vassals may still speak on matters that concern others, for example
their own vassals. It is not unheard of for circles of allegiance to
form (A is lord of B is lord of C is lord of A). All this, and the fact
that Blood of the City can be quite unified if there is a threat, makes
the court difficult and trying to deal with.

[The Director](The_Director "wikilink") is a Jaggling member the players
have dealt with.


=== Cat spirits

The [pack](pack "wikilink") has friendly ties towards cat spirits, a
part of the [Urban Ronins](Urban_Ronins "wikilink"), not only because
the [totem](totem "wikilink") is a cat spirit. The pack also protects
the cats in the sewer mazes from attacks of the dog spirits. In
exchange, the cats act as information gatherers and disseminaters.


=== Concrete wood

Concrete wood is a [spirit court](spirits "wikilink") encompassing the
"bones" of the city: buildings, streets, channels, etc. As in real life
and as the trees in a wood, the court is omnipresent (and quite vital to
the existence of the city's Hisil denisens), but not very active or
powerful. Most spirits are greater Gafflings, but they are totally fixed
on their sorroundings, ignorant to the going-ons outside their houses.

The court seems organised in "neighbourhoods", which encompass all
members in a certain area and are supposed to be able to communicate
(painfully slowly). Most buildings of importance have spirits that leave
this court to join a more active one; therefore there are almost no
Jaggling members.

=== Court of Eternal Grace

A [spirit court](spirits "wikilink") concerned with the arts, culture
and associated things. It is unclear how far exactly the domain of this
court goes, but given that it is quite powerful and many of the old
historical buildings also belong to it, it might even encompass nobility
and similar cnocepts. The pack came into contact with the court during
the events of [the old werewolf's last
play](the_old_werewolf's_last_play "wikilink"). Possibly, [Prince
Yaromir](Prince_Yaromir "wikilink") is a member of this court. Other
likely members include the spirit known as [Meister im
Norden](Meister_im_Norden "wikilink") and [the Bleeding
Stone](the_Bleeding_Stone "wikilink").
[Kaffeehaus](Kaffeehaus "wikilink"), the spirit of [Café
Alexanderplatz](Café_Alexanderplatz "wikilink"), is a member of this
court allied with the pack.

The court has a mixed history with the pack, acting as opponent during
[the old werewolf's last play](the_old_werewolf's_last_play "wikilink"),
as advisors during [the fate of The Bleeding
Stone](the_fate_of_The_Bleeding_Stone "wikilink") and recently as an
ally during the events at [Petersburg
Wilhelmplatz](Petersburg_Wilhelmplatz "wikilink"), then using them in
[reality theatre](reality_theatre "wikilink").

The pack has learned that the Jaggling members of this court tend to
build domains for themselves in retreats in the Shadow, places that have
no direct physical reflection, and rarely leave them. Interestingly, the
broods of those Jagglings often contain members of other courts.
Politics seem to be on an individual basis with the Jaggling members.

It is assumed that all Jaggling members of this court are also members
of [the High Court of
Petersburg](the_High_Court_of_Petersburg "wikilink"). The court has an
old alliance to the [Urban Ronins](Urban_Ronins "wikilink"), but is in
conflict with the new stronger courts, [Fleshmade](Fleshmade "wikilink")
and [Blood of the City](Blood_of_the_City "wikilink").

The [Steel Predators](Steel_Predators "wikilink") have an old feud with
this court, something about a broken deal a century ago.


=== Die Flüssigen

A large spirit court encompassing all spirits that deal with water in
all its forms -- rain, rivers, probably even tears and sweat, though
only in a very minor way.


=== Fleshmade

Fleshmade is a [spirit court](Spirits "wikilink") nominally encompassing
all items made by mankind. Since the court is quite new (it emerged
during the final phases of industrialisation with the advent of mass
production), this claim is quite far from reality: Everything that
already existed belonged to other courts (mainly [Blood of the
City](Blood_of_the_City "wikilink") and [Court of Eternal
Grace](Court_of_Eternal_Grace "wikilink")). Thus the court started in a
niche, encompassing the "soulless" mass-produced items. These have
become very common, though, and so the Court has grown in power and
seems to be among the top players today. It is still easy not to notice
it, though.

Today, the spirits of the court usually belong to items that are
considered to lack 'identity' (everything humans usually don't have a
personal connection to), and associated conceptual spirits. Due to its
(relatively) fast rise to power and conflicting claims, the court has
many enemies, especially among the more powerful courts.

The pack has found the spirit of the pharmacy at
[Wilhelmplatz](Wilhelmplatz "wikilink") hiding as a Ridden. They gave it
to [Blood of the City](Blood_of_the_City "wikilink") to gain favour with
the court.


=== Grey Court

A powerful yet fractured spirit court. It is related to negative
emotions, but not to violent ones - gloom, despair and fear seem to be
most prevalent. It is likely the most powerful court in the pack's
territory, but it has almost no unity - there are some more powerful
spirits in this court who are in fierce competition for followers.
Prominent members include
[She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink") and
[Pitch Black](Pitch_Black "wikilink").

Another powerful member was the previous owner of the pack's
[locus](old_radio "wikilink"), but it was destroyed by the pack.


=== Handmaidens of Bloodshed

A spirit court of mercenaries, who sell their services for essence.
Known appearances are crouched,black figures with shotguns or
knives/swords as arms.


=== Legion

Legion is a [spirit court](Spirits "wikilink") consisting of insects,
invertebrae and associated concepts. It is easily overseen and likely
not very powerful. Spirits of insects that work in groups or swarms can
sometimes be found - they consist of hundreds of animals and move with a
characteristic noise. For solitary insects, only rumours exist.

The pack has met one cockroach spirit during the events at [Petersburg
Wilhelmplatz](Petersburg_Wilhelmplatz "wikilink"), but had no other
contact with the court so far.


=== Network

A spirit court. Not much is known of these, but the
[EepEep](EepEep "wikilink") are part of them, as likely is [Großer
Sirocool](Großer_Sirocool "wikilink").


=== Rote Hof

A spirit court in the sewers. Encompasses discordance, warriors,
violence, lust, torture, knives, pain (rags as a sign of pain),
perverts. Situated at the Abyss. One known Spirit was [Schleier des
Vergessens](Schleier_des_Vergessens "wikilink"), who fled and whose
whereabouts are unknown.


=== Spirits of Fire and Steel

A spirit court situated at the [steel
works](Drnaya_Steel_Works "wikilink") in the pack's territory. The court
is large and very powerful, but stay within their borders (at least
while the pack stays out of theirs). They do not allow access to the
court's territory and are believed to kill on sight. They are known to
have at least one [locus in the
steelworks](locus_in_the_steelworks "wikilink").

Also semi part of this court is the locus in the pack's territory, in
[Angus](Angus "wikilink")' living area. A [locus of Hearth and
Homeliness](Heimeligkeitsfenster "wikilink"), where hobos meet and can
warm themselves. Due to the dual nature of home, fire and buildings,
this is future battleground. The pack has secured right of passage in
the Hearth locus.

=== Spirits of Order

A spirit court, known to encompass the police. Allied with the
[Network](Network "wikilink").

=== Steel Predators

Spirits normally encompassing cars and trucks. Steel Predators have a
territory where they feed on prey. They are usually lone spirits. The
[pack](pack "wikilink") had dealings with a Jaggling spirit
*[T-34](T-34 "wikilink")*, and the [Steel
Spider](Steel_Spider "wikilink").


=== The High Court of St Petersburg

It seems there is a court of spirits of Jaggling Rank, meeting at the
[Palace Square](Palace_Square "wikilink") on nights where the moon is
split. This court can issue decisions on its members, known as a trial
by peers. The spirits seem to adhere by this decisions.

Werewolves - those that are of Jaggling rank - avoid the court. This is
due to the fact that any participator is deemed a member, and therefore
also subject to rulings of the court. No sane Forsaken wants to submit
himself to the rulings of a bunch of Jagglings.

The [pack](Shadowclaws "wikilink")
[once](The_fate_of_The_Bleeding_Stone "wikilink") persuaded a number of
members of the court to jugde a [spirit](The_Bleeding_Stone "wikilink")
for them. None of them has been to the court, and none has the rank
required.

=== Urban Ronins

A [court](spirits "wikilink") consisting of the spirits of larger
animals (mainly cats, birds, dogs) that live in the city. The spirits
are usually quite solitary (even the dogs) and quite paranoid. It is
rumoured they will not accept gifts of essence, a behaviour stemming
from a number of attempts by the city's population to kill their
physical counterparts by laying out poisoned food.

The pack has good connections in particular to the [Cat
Spirits](Cat_Spirits "wikilink"), since their [totem](totem "wikilink")
comes from this brood. The dogs are therefore natural opponents, while
most birds seem content to ignore them.

This court has traditionally good ties with the [Court of Eternal
Grace](Court_of_Eternal_Grace "wikilink") -- a rare thing in the spirit
world.

=== Violent Ones

The Violent Ones are a court composed of spirits of - how else could it
be - violence and violent feelings. They are quite strong, yet due to
their nature they are not very united. They are very aggressive, and
usually cannot be bargained with. It is not clear if this is the same
court as the [Roter Hof](Roter_Hof "wikilink") or another one. It seems,
though, that the latter is restricted to the area below [Bar
Strocic](Bar_Strocic "wikilink").
