=== Athumu

High ranking sewer spirit with an associated court, most likely part of
the [water spirits](Die_Flüssigen "wikilink"). Was disposed by the
[Great Slimy One](Great_Slimy_One "wikilink") using a weapon, a ridden,
that was delivered to him by the pack.

=== Cinema Spirit

The spirit of the local [cinema](Spartak_cinema "wikilink"), of assumed
Jaggling rank. The pack has had some fairly reasonable contacts with it.
The spirit helped the pack create a large amount of darkness essence, to
lure and ultimately kill a darkness spirit. Recently, the pack has
learned of the theatre spirits from the Cinema Spirit. Angus is
re-viving a [cinema club](cinema_club "wikilink") as part of the
payment.

=== Daemonium

A spirit of St. Petersburg, suffering and violence. It embodies the
aspect of the city as a place built on the blood of innocents, a
battlefield, and the centre of an emerging military power. It seems to
have once been allied to the Pure, but since the reconquest of the city
by the Forsaken no werewolf has seen it.


=== EepEeps

Information spirits friendly to the pack. They call the pack's main
[locus](Old_radio "wikilink") their home and have made a deal with the
pack encompassing the following points:

  - The pack will protect the EepEeps from other spirits.
  - The pack owns the locus, giving them free access anytime they want.
  - The EepEeps are entitled to half the essence generated by the locus.
    They inform the pack if there is trouble on their side of the locus.

=== Eternal Grace

A name applying to two highly ranked members of the [court of Eternal
Grace](court_of_Eternal_Grace "wikilink"): [Prince
Yaromir](Prince_Yaromir "wikilink") and [the
maiden](the_maiden "wikilink"). Why exactly that is and if there is any
sensible reason remains to be seen.


=== Giftläufer

Spirits in the service of the [Great Slimy
One](Great_Slimy_One "wikilink"). Their ban is known: a specific weed
that makes them wary to attack.

=== Great Slimy One

The 'Great Slimy One' was a lesser Jaggling that manifested in the
sewers due to the biological waste [transported there by some criminal
elements](fight_in_the_sewers "wikilink"). It quickly took over the main
locus in the sewers (situated right on the origin of the contamination),
replacing [Athumu](Athumu "wikilink"), and established its own court. In
the following weeks, the court grew stronger and stronger, until it was
the predominant court throughout most of the sewers.

The [Giftläufer](Giftläufer "wikilink") were a kind of spirit that
provided muscle for his court, and an enemy the pack repeatedly faced.

He was eventually discorporated by the pack and subsequently destroyed
during the [cleansing of its locus](fight_in_the_sewers "wikilink").


=== Großer Sirocool

A spirit of a great hacker. Believed to be of Jaggling rank, very
possibly Greater Jaggling. Might be part of the
[Network](Network "wikilink") court.


=== Kaffeehaus

The [spirit](spirits "wikilink") of [Café
Alexanderplatz](Café_Alexanderplatz "wikilink"), a member of the [Court
of Eternal Grace](Court_of_Eternal_Grace "wikilink"). It previously was
the spirit of another café that became collateral damage during [the
fate of The Bleeding Stone](the_fate_of_The_Bleeding_Stone "wikilink").
The [pack](Shadowclaws "wikilink") has convinced it to try and remove
the barren; they have gathered and coerced spirits for its brood or for
consumption and provided essence and security, both themselves and via a
deal with [Blood of the City](Blood_of_the_City "wikilink").

Kaffeehaus is of greater Gaffling rank, probably of medium power among
greater Gafflings.


=== Meister im Norden

Enigmatic and mostly unknown high-ranking spirit in the
[sewers](sewers "wikilink"). Is believed to be a spirit of the times of
old, smuggling and taking no orders.


=== Nevskys Sword

Nevskys Sword is a [Steel Predator](Steel_Predators "wikilink"), the
[spirit](spirits "wikilink") of the [Alexander Nevsky
Bridge](http://en.wikipedia.org/wiki/Alexander_Nevsky_Bridge) located at
the eastern border of the no-mans-land, bordering the
[Glasfelle](Glasfelle "wikilink") territory and close to the [Crimson
Tears](Crimson_Tears "wikilink"). Still, its influence stretches right
to the current eastern border of the
[Shadowclaws](Shadowclaws "wikilink").

The spirit is very powerful, its name evokes a certain awe in the Hisil
of Petersburg. According to [Andrei
Wind-in-den-Straßen](Andrei_Wind-in-den-Straßen "wikilink"), it is of
Greater Jaggling rank and he and his pack go to a certain length to
prevent provocating it. He says the name is from a famous quote of the
russian hero Alexander Nevsky, namesake of the bridge: "He who comes to
us with a sword, from a sword will perish.". The bridge feeds on all
passing spirits, and it has a number of "spirit packs" at its service
that drive or lure prey to the bridge, feeding on the scraps left by the
powerful Jaggling.

=== Pitch Black

Pitch Black is a spirit of the [Grey Court](Grey_Court "wikilink"), a
rival of
[She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink").
Little is known about him, but he must be of Jaggling Rank.

=== Prince of the River

A very high-ranking spirit, of at least Jaggling rank, quite possibly
higher. He most likely belongs the court of [water
spirits](Die_Flüssigen "wikilink") The pack owes him four favours, of
unspecified duration and level of danger. For these favours, the Prince
helped the pack with the rite to cleanse the [Great Slimy
One's](Great_Slimy_One "wikilink") locus, providing five lesser
Gafflings that would be destroyed in the process. The bargaining only
implied that these favours have to at least theoretically be possible
for the pack to achieve.

One of the five favours was [called
in](The_fate_of_The_Bleeding_Stone "wikilink") recently, giving the pack
the opportunity to get free of all of them - which they chose not to do.

=== Prince Yaromir

A spirit of a [now-destroyed
theatre](garbage-burning_facility "wikilink") of at Greater Jaggling
rank. It seems Prince Yaromir is a spirit of acting and theater in
general, a fact he [impressively displayed](reality_theatre "wikilink")
by manipulating the werewolves of Petersburg so they unwittingly
participated in a play designed to strengthen his
[court](Court_of_Eternal_Grace "wikilink").

Probably not coincidently, this is also the name of the male main
character of a famous (in Russia, that is) russian theatre play, based
on an old tale.

Strangely, another name this spirit goes by is [Eternal
Grace](Eternal_Grace "wikilink") - a name shared by another Greater
Jaggling of his court, [the maiden](the_maiden "wikilink").


=== Rahglu

A strange breed of spirit and flesh, the Rhaglu appear as sheep-sized
wasps. Little is known about them, and it took Angus days to find their
name even with help of the [Enlightened](Enlightened "wikilink"). The
few facts that are known are:

  - They are not Spirits (at least not fully). The Ithalunim did not
    even know the names of them.
  - They seem to posses strength in numbers. A lone Rhaglu is weak, but
    when the [pack](Shadowclaws "wikilink") was
    [ambushed](Breeding_Grounds "wikilink") by 7 of them it was almost
    wiped out.
  - They have a hive-like structure, as there are many underneath [St.
    Nicholaus Cathedral](St._Nicholaus_Cathedral "wikilink"). At least 3
    types exist: Simple 'workers' wo make up the majority, fierce
    warriors wo seem primarily concerned with protecting the nest, and
    queens which probably function as some sort of hive mind, as she is
    not needed for laying eggs.
  - They procreate by laying eggs into humans, which then hatch within
    about a month, consuming their hosts. They favour wolfblooded since
    these have a higher-than-average stamina, allowing for more eggs to
    successfully hatch. All workers can lay eggs, not only the queen.
  - They have a basic understanding of human society, hiding their
    victims and acting as to not draw too much attention.
  - They seem to communicate based on scent, and supernaturally strong
    odours are known to disrupt their unity, making them far easier to
    battle.


=== Schleier des Vergessens

    A spirit of the [Roter Hof](Roter_Hof "wikilink"), escaped during the
    pack's watch of the access to the Abyss.

=== She Who Was Eternally Lost

    A spirit of lesser Jaggling rank, also known as "lost Daughter". She
    embodies the concepts of mourning and fear of losing someone/something.
    She often appears as a large foetus in red clothes. Her first concept
    was the spirits of the aborted children of prostitutes, hence her
    appearance. Originally she was part of the [Red
    Choir](Red_Choir "wikilink"), but she escaped during the events of the
    [fight in the sewers](fight_in_the_sewers "wikilink"). There currently
    seems to be some infighting in [her court](Grey_Court "wikilink").

    The pack (or rather [Aleksandr](Aleksandr "wikilink") bargaining
    generously on the pack's behalf) made a deal with it, to save
    [Ivana](Ivana "wikilink")'s life. The deal is valid as long as Ivana
    lives, so the pack has a safe way out should the need arise. Aleksandr
    would probably oppose it, but [Angus](Angus "wikilink") seems quite
    willing to use this threat at least as a bargaining chip.

    The deal compromises the following points:

      - Both parties will refrain from any path of action that could lead to
        direct attacks on the other parties. This is basically a
        non-aggression treaty with the added security of not being allowed
        to use third parties against one another.
      - The pack will be allowed to use her main
        [locus](Black_locus "wikilink") to cross the Gauntlet, and the
        Werewolves are entitled to a third of the essence generated by the
        locus.
      - In return, the werewolves are bound by oath to help defend the locus
        in rough times, to fight their common enemies from the [Grey
        Court](Grey_Court "wikilink") and to assist her in tracking down
        spirits of her retinue that go rogue.

    [Recently](Breeding_Grounds "wikilink"), the spirit has acquired another
    [locus](old_altar "wikilink"), and gained control from the
    [Rahglu](Rahglu "wikilink"). She-Who-Was–Eternally-Lost is now a name
    that is not spoken lightly in the Hisil of the pack's territory.

=== Steel Spider

    A spirit whose help was enlisted to fight against the [Great Slimy
    One](Great_Slimy_One "wikilink"). Has since this fight risen to Jaggling
    rank.

    The spirit was part of the "Geschaffenen" or possibly "Beständigen"
    court, and quite Independent. It has changed allegiance to the [Steel
    Predators](Steel_Predators "wikilink") during the events sorrounding
    [the fate of The Bleeding
    Stone](the_fate_of_The_Bleeding_Stone "wikilink"), allowing it to escape
    a deal with the [Court of Eternal
    Grace](Court_of_Eternal_Grace "wikilink") which bound it to servitude.

    It is now bound to a sewage cleaning vehicle employed by the [St
    Petersburg Sewage and Waste
    Authority](St_Petersburg_Sewage_and_Waste_Authority "wikilink"). It
    preys on anything smaller than itself in the Sewers, and claims them as
    its hunting ground, actively resisting other Steel Predators that would
    try to occupy it.

=== T-34

    The spirit of a large truck, preying on smaller vehicles, stray animals,
    and pedestrians. It is not known for its Finesse. A member of the [Steel
    Predators](Steel_Predators "wikilink").

    T-34 is a lone spirit, claiming a territory encompassing that of the
    Shadowclaws, stopping outside the [Drnaya Steel
    Works](Drnaya_Steel_Works "wikilink").

=== The Bleeding Stone

    A Jaggling in the pack's territory. Associated with one of two legends:

    ((will follow))

=== The Director

    A Jaggling member of [Blood of the City](Blood_of_the_City "wikilink"),
    the pack had dealings with him twice, both times to lend larger amounts
    of essence they couldn't find themselves. He usually negotiates via a
    Gaffling member of his Court and doesn't show up "in person".


=== The Maiden

    The maiden is a greater Jaggling of pure beauty - a very rare breed of
    spirit associated with truth, purity and beauty. Her mere presence seems
    to have a strong impact on spirits of negative emotions, and it appears
    she has Numina capable of freeing a werewolf from the grip of Kuruth.

    Spirits of positive emotions or concepts are rather rare in the Hisil of
    the World of Darkness, and usually have a slim chance of existing for
    any prolonged period. There are just to many spirits of opposing
    concepts that ruthlessly hunt and destroy them. Finding even a lesser
    Jaggling from those ranks is no easy task, so she is probably the only
    greater Jaggling of her choir in western (or even all of) russia.

    The maiden belongs to the [court of Eternal
    Grace](court_of_Eternal_Grace "wikilink") and is hidden in a complicated
    web of pockets in the Hisil of the [Twin
    Palaces](Twin_Palaces "wikilink"). It appears her combat capabilities
    are rather weak for a greater Jaggling.

    She was recently involved in a [play](reality_theatre "wikilink") staged
    by [Prince Yaromir](Prince_Yaromir "wikilink"), another Jaggling of her
    court, designed to bring [the Bleeding
    Stone](the_Bleeding_Stone "wikilink") over to the court. Strangely
    enough, [Angus](Angus "wikilink") learned that another name for her
    might be [Eternal Grace](Eternal_Grace "wikilink"), a name that also
    applies to [Prince Yaromir](Prince_Yaromir "wikilink").

=== The Son and the Nephew

Two very weird [spirits](spirits "wikilink") that are reflections of a
    riot at [Wilhelmplatz](Wilhelmplatz "wikilink") some 150 years ago. They
    appear in the weeks preceding the anniversary of the riot and start
    recruiting local spirits to their cause. How exactly this recruitment
    works is unclear, but it is on a subconscious basis and even affects
    werewolves. Recruits feel a strong urge to fight for their master, and
    are usually motivated by a promise of essence and feeding opportunities.
    The two parties clash on the date at Wilhelmplatz, were many spirits are
    discorporated and the area is drained of essence. This has led to the
    formation of a Barren.

    The followers of Son and Nephew consist entirely of Gafflings - it is
    unclear if this is due to the fact that Jagglings can feel the influence
    and leave the area beforehand or if they are immune. Still, the entire
    area is split among their followers and the widespread destruction will
    not spare anyone who declares no allegiance to either.

    Following [recent events](Petersburg_Wilhelmplatz "wikilink"), the
    combat between the two spirits has been ritualised, the pack providing a
    combatant and the price (a greater Gaffling). As such, the growth of the
    Barren has been stopped, yet there is still a spiritual wasteland that
    will take much effort to remove ... and it remains to be seen what
becomes of the two spirits.

=== Window to the West

A spirit of St. Petersburg, lore, and learning. Embodies the aspecet of
the city as a window towards a more enlightened world, and as a place of
progress. It is the patron totem of the
[Enlightened](Enlightened "wikilink"), but has only a very small court
after more than a century of persecution by the Pure.

=== Wissendes Auge der Nacht

Wissendes Auge der Nacht is a stray cat spirit encountered by the pack
during their rite of initiation. After the spirit repeatedly stole
essence from an area the pack was guarding, they tracked it down and
gave it a simple choice: Become our totem or perish.

Wissendes Auge der Nacht does not trust easily - as is reflected in its
ban. The initial relationship with the pack was quite strained, given
the blunders the newly changed werewolves made during their first
dealings with the spirit wild. However, as they worked toward securing
their territory, the spirit became a valuable ally, particularly in
their struggle against the [Great Slimy
One](Great_Slimy_One "wikilink").

The Chorus Numina allows Wissendes Auge der Nacht to call upon other
[cat spirits](Cat_Spirits "wikilink") in the territory.

==== Stats

**Attributes:** Power 2, Finesse 4, Resistance 3
**Willpower:** 5
**Essence:** 15
**Initiative:** 7
**Defence:** 4
**Speed:** 13
**Size:** 2
**Corpus:** 5
**Influences:** Cats 1, Shadows 1
**Numina:** Material Vision, Chorus
**Bonuses:** Brawl +1 (given); Stealth +2 (pack); Occult +2 (story)
**Ban:** the pack may only eat meat hunted by themselves
