= Cool stuff in the new 2.0 rules

* The pack is far more in focus, with Wolfblooded and other "pack members" (allies, contacts, etc) having a more important role.
* Each of the five shapeshift forms now has a unique role to play, and unique advantages. Social skills are no longer penalised.
* Primal Urge is more meaningful and ties in better with the Spirit/Werewolf side.
* Gifts are very cool and it's easier to pick the ones you like. They are tied to your Renown now as well, giving each character more flavour.


== Converting your character

=== Attributes,  Skills, and Renown

These stay unchanged.


=== Merits

Generally these stay unchanged. Merits might need to be updated to the new version (especially Fighting Styles), see the https://www.drivethrurpg.com/product/114078/World-of-Darkness-GodMachine-Rules-Update[nWoD2.0 Rules Update] for a full list of Merits. Talk to your GM to find a meaningful conversion if dots change by a lot, or if the benefit changed substantially.


=== Gifts

Tally your Gifts. Check which Giftlists you have activated, and note these down. Then, pick the same number of Facets that you had from any or all of the  Giftlists you had activated. Note that you cannot activate a Facet if you do not have the corresponding Renown.


=== Rites

NOTE: Every character now starts with two dots to buy Rites with. Pick the ones you want.

If you had Rite dots before, convert these into Gifts of your Affinity Giftlists. Convert the Rites' ratings you had into an equal amount of new Rites.

Talk to your GM if you if you want to change some things around. There is no  "the only Ritemaster of the pack" in 2.0, so your character concept might need some tuning.


=== Harmony

Start at a Harmony "away from five" (any direction) the same distance you are "away from seven" in the old system. Discuss with your GM if you'd like to change this. We assume people will make reasonable choices based on character background.


=== Totem

Leave it as it is for now. Maybe we will run a totem-focused story at some future point; we can discuss conversion then.


== New stuff

You have 10(?) points to spend on new *Merits*, *Father Wolf Gifts*, and/or *Rites*. This is to compensate for the generally cheaper advancement, and because these offer cool new ways to customise your werewolf in the new system. Especially check out the new Merits for Tribe and Auspice specific Merits and Rites, and the new Fighting Styles.

Pick a physical Touchstone for your character; mostly this will be a person or group that you have as part of your character background anyway.


== Remaining "old XP"

NOTE: This rule also applies to your Renown XP. Note that you could gain a Renown dot if you had a high enough amount of Renown XP.

Your old XP are converted to Beats on a one-to-one basis. Five Beats are one new XP.


== Final Touches

It's best you try you new character out once: Note down how your new character compares to your old and discuss with the GM if you're (un)happy!
