= Houserules

== Kuruth

* grab all triggers, and give bonus to Common/penalties to Specific ones?
* should all werewolves have the same triggers, or should there be some variation?

=== Additional Checks

* All triggers at once might be a bit too many? Or do you mean all triggers of the chosen set, with +/- 2 on specific/common ones? that might work, but how does harmony then play into it?
* Kritischer Erfolg im Angriff: Kommt seltener vor (höhere Defence), aber gerade in Gauru durchaus denkbar.
* 5+/6+ Schaden erhalten von einem Angriff: Kann öfter vorkommen im neuen system? Zu arg? Last health box checked with lethal might still be one? Oder einfach critical success für Gegner?
* Packmates Down (filled with lethal damage). Similar, but not identical with Pack trigger.
* how about a penalty per Harmony? 5: 0, 6-7: -1, 8-9: -2, 10: -3 (und radialsymetrisch)?
* Personal trigger: hat eigentlich schon was; evtl. die ganz krassen etwas abschwächen.

NOTE: Personal Triggers muss man max einmal pro Nacht resisten (steht so beiläufig im schwarzen Kasten)!

---> Vorschlag: Persönliche Trigger lassen, alle aktiv mit Bonus/Abzug; general Triggers erweitern. Harmony-Einfluss: General Triggers? Eventuell die Trigger aus dem alten Werewolf wieder übernehmen, die hatten auch Bezug zur Harmony?


== Touchstones

Touchstones are wonderful plot hooks and opportunities for meaningful interactions with the game world. We'll easily be time constrained if we have two per player, though.

All players start with the same _Totem_/_Wild_ als spiritual Touchstone. Physical Touchstones are chosen individually for each character.


== Breaking points

We'd like to increase the number of Breaking Points. The idea in Book seems to be that anything drawing you to spiritual side is BP towards Spirit, anything drawing to physical side is BP towards flesh.

However, most rolls seem to be based on denying the other side; what if _fulfilling one_ were also a Breaking Point? Extensive Gift usage a Breaking Point towards spirit, mundane solutions using advanced tools towards flesh, the apex of a challenging _Siskur-Dah_ towards spirit, a night out with the boys towards flesh? Probably this shouldn't be hard-coded as that would be an endless list and lots of bookkeeping, but if we keep an eye on it during play?

There is also a paragraph on personal Breaking Points which sounds promising, but will we manage to implement them?


== Conditions

Ignore and apply common sense where applicable. Some Gifts/effects/etc will need additional rules. These are listed here.

If in doubt, a positive condition adds +2 to a suitable dice pool, a negative one subtracts.

* Lunacy Conditions
* Lash out Aura
* Hunter's Aspect


== Old Houserules

=== Botches

Rolling at least 50% 1s on a roll *without a single success* is a
critical failure.

=== Renown XP

Renown XP is doled out by the storyteller for specific actions and
cannot be bought using regular XP.

=== Languages

A score of \* in a language allows everyday conversation, and sufficient
reading/writing to get along. A score of \*\* allows full fluency, at a
level of a native speaker, yet with a (possibly slight) accent that
tells listeners you're a non-native speaker. A score of \*\*\* allows
for the active use of different dialects, full command of the language
and an extensive vocabulary. With this level it is possible to fool
almost all people into believing you are a native speaker. Most native
speakers do not have this level of proficiency.

=== Damage and Wound Penalties

The first health box is always without penalty. The last *two* health
boxes are at -3, the two before that at -2 penalty. All remaining health
boxes are at -1 penalty. The number of these boxes depends on the total
number of health boxes available.

=== Claws and Teeth Damage

Werewolves in Gauru form get +2(L) claws damage and +3(L) bite damage.
Urshul claws do +0(L) damage, Urhan +0(B). Both Urshul's and Urhan's
bite attacks are at +1(L).

=== Rite of Contrition

This Rite is a level 1 rite, but may only be used personally. It can not
be performed on someone else's behalf. (The Book was unclear on the
second part)

=== Rite of the Chosen Ground

This rite no longer requires a locus, it can also be performed with
other objects as focal point. If the focal point is not a locus, the
following restrictions apply:

  - The object must have a spirit of at least Greater Gaffling rank,
    which has to cooperate throughout the rite
  - The spirit (and object) must be aligned with the kind of resonance
    sought (e.g., a white flag for "peacefulness" or "french")
  - The area affected spreads out from the object with the same radius
    that a locus of equal rank to the spirit would have (i.e., two yards
    for a lesser gaffling, 15 for a greater gaffling, up to a city block
    for a minor god). There is no factor of 3, as the "boost" from the
    locus is lacking

=== Loci

A locus can not be 'sucked dry' - that is just too simple a way of
destroying it. As soon as the stored essence runs out, no more can be
extracted.

=== Helping Another

Instead of rolling when aiding another, the recipient gains a flat
number of bonus dice equal to 1/3 the dice of his aide (rounded real).
You can not help another if you do not possess the fitting skill (even
if you have Int 6, without Crafts you're not going to be any help
repairing a motorcycle).

=== Wolf Fighting Styles, Pack Tactics

See the [Pack Tactics, Tactical Combats and
Complexity](Pack_Tactics,_Tactical_Combats_and_Complexity "wikilink")
page.
