= Loci

A locus is a powerful place where the gauntlet is very thin. As a
result, essence is generated, and crossing between the material and
spirit world is far easier (for many beings, it is only possible at
loci).

Therefore, loci are focus points of supernatural conflict in the world
of werewolf: Spirits and werewolves seek them as power bases, and others
might be drawn here due to their resonance.

|                                                               |
| :-----------------------------------------------------------: |
|   A list of known loci in Petersburg in alphabetical order:   |
|                             Name                              |
|             [Black locus](Black_locus "wikilink")             |
|    [Heimeligkeitsfenster](Heimeligkeitsfenster "wikilink")    |
| [Locus in the steelworks](Locus_in_the_steelworks "wikilink") |
|               [Old altar](Old_altar "wikilink")               |
|               [Old radio](Old_radio "wikilink")               |
|             [Sewer locus](Sewer_locus "wikilink")             |
|     [Smuggler's treasure](Smuggler's_treasure "wikilink")     |
|            [Summer Gates](Summer_Gates "wikilink")            |

== Black Locus

A bit to the southwest of the packs main locus, in the same shabby
housing area, is another, smaller locus. When the pack first moved in,
this locus was attuned to depression, decay and hopelessness. It was
here that the young, inexperienced werewolves were almost annihilated
when they were ambushed by the spirit that claimed the locus. In the
following struggle, the werewolves were able to beat their opponent with
the help of the [Spirits of Fire and
Steel](Spirits_of_Fire_and_Steel "wikilink") and a special weapon
exploiting the spirit's ban. The locus, as was a condition for the aid
of the powerful court, was destroyed in the process, and lay dormant for
quite a while.

When [She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink")
escaped from the [red court](Roter_Hof "wikilink"), she was drawn to the
area of the locus. After her deal with the pack exempt her from
prosecution by the werewolves, she began to settle in and form a
powerbase of her own. The locus has since reappeared a few meters
further, inside a small orthodox chapel (the locus' physical
manifestation is the crucifix at the wall behind the altar). It seems to
be attuned to feelings of loss, and the fear associated with them. The
air in the building is correspondingly gloomy, yet many of the locals go
here to pray for lost loved ones, or to be alone with their grief.


== Heimeligkeitsfenster

A locus of Hearth and Homeliness, in [Angus](Angus "wikilink")'s living
area. Situated in a ruined building, hobos meet and can warm themselves
at a small fireplace, which is also the locus. The pack has secured
right of passage for this locus, but anything going beyond this will
ensure the wrath of the [Spirits of Fire and
Steel](Spirits_of_Fire_and_Steel "wikilink").


== Steelworks

There is a (possibly quite powerful) locus in the steelworks that form
the western part of the pack's territory. It is claimed by the [court of
fire and steel](Spirits_of_Fire_and_Steel "wikilink"), as is the
[Heimeligkeitsfenster](Heimeligkeitsfenster "wikilink"). The pack knows
almost nothing about the window, and the spirits have made it clear that
any unannounced intrusions into their territory will be met with lethal
force.


== Old Altar

Beneath the [St. Nicholaus
Cathedral](St._Nicholaus_Cathedral "wikilink"), in a number of extensive
cellars, lies an altar that is a [locus](locus "wikilink"). It's
resonance was a very weird (and oddly specific) one, best described by
"sacrifice (of others) for personal gain". [Angus](Angus "wikilink")
performed a rite here to change the resonance, and with the help of
[She-Who-Was-Eternally-Lost](She-Who-Was-Eternally-Lost "wikilink") the
locus now has a resonance more focused on "personal sacrifice",
something very close to the spirit. The strength of the locus is
unknown, as its physical part is off limits currently.


== Old Radio

The packs main Locus is situated in an old building in the southeast of
their territory. Both the Locus and the building have seen quite some
action since the pack moved into this area.

The Locus, at the moment manifested in a computer, is aligned with
'information'. It seems that during the Siege of the City, one of the
few working radios was in this room, where family, friends and
neighbours all would gather to catch up on how the war was progressing
(or, at least, how the Soviet press claimed it was progressing). The
essence lingering in the area finally formed a locus, which manifested
in the radio. The building served as a workshop for car repairs on the
lower floor, while the family lived on the upper floor.

In the nineties, there was a downward trend in the area, and the
workshop was closed. The building soon afterwards became home to a local
gang, which occupied it until recently.

When the pack found out about the locus, not only did they face the
problem of somehow removing or convincing the gang. As it turned out, a
not too kind spirit made of shadows and despair, commanding a smaller
spirit court, had claimed the locus its own. The young werewolfs learned
the hard way just how unwelcome they were in the Hisil.

The mundane site of the problem was easily dealt with: The packs
[Irraka](Aleksandr "wikilink") infiltrated the building one night and
silently took out the head of the gang. Next evening, the pack attacked
the now leaderless gang and more or less wiped them out. Only a few
weeks later, the building was claimed for the newly-founded [St
Petersburg Sewage and Waste
Authority](St_Petersburg_Sewage_and_Waste_Authority "wikilink") in the
area, with both [Grigori](Grigori "wikilink") and
[Angus](Angus "wikilink") as employees.

As it turned out, the spirit side was not quite as easily dealt with.
After a crushing defeat at the hands of their enemy that almost cost
[Grigor](Grigor "wikilink") his life, the pack went out to search for a
weak spot of their enemy. They learned the spirits ban and fashioned a
weapon to exploit it. Even then, their Cahalith warned them against a
frontal assault, so they made a deal with a movie theatre and laid a
trap for their enemy.

After honouring their side of the deal - hunting down a rogue spirit
that had escaped into the mundane world - they arranged for a blackout
during the premiere of the newest movie, generating a large amount of
darkness-affiliated essence. As predicted, their enemy could not resist
such a meal and showed up with only a light escort. The trap was sprung,
and the pack charged their enemies as one. The fighting was fierce, but
the weapon fashioned against the spirits ban gave their Rahu the
decisive edge in the struggle, and this time he came out on top.

The locus was now the packs to command, and they quickly entered an
agreement with a few information-spirits called
[EepEeps](EepEep "wikilink") that resided there. This agreement stands
to this day, even though it was almost cancelled during the infiltration
by [Rote Wut](Rote_Wut "wikilink").


== Sewer Locus

There is a big locus in the sewers of Admiralteyski. It has been the
place of the pack's fight against the [Great Slimy
One](Great_Slimy_One "wikilink"). It is not known if this locus existed
before the coming of the waste spirit, or if both were in fact created
by the [disposal of hazardous waste into the
sewers](fight_in_the_sewers "wikilink"). The locus was aligned to fresh
water by a complicated ritual performed by [Angus](Angus "wikilink"),
and is now fiercely contested by the sewers spirit population. The pack
has kept out of the fighting for the time being, content that the
spirits are busy with one another and no threat to their territory at
the moment.

== Smuggler's Treasure

There is a locus belonging to the enigmatic spirit residing in some
parallel of the sewers northern Hisil. It seemed to be aligned with
smuggling, but little more is known.


== Summer Gates

The gates to the [Summer Garden](Summer_Garden "wikilink") are a
[locus](locus "wikilink") - the pack realised this when
[pursuing](The_fate_of_The_Bleeding_Stone#Final:_Hunt! "wikilink")
fleeing Ridden. It is unclear what their attunement is, or who claims
the locus.
