= Other humans

This is an overview of all important Characters in the Saga. Note that
only inhabitants of the physical world are listed here. For the strange
inhabitants of the Hisil, see [Spirits](Spirits "wikilink").

## Werewolves

There is an [alliance](alliance "wikilink") of Forsaken in the city,
trying to keep internal quarrel to a minimum. It's a very loose society,
mostly held together by the constant threat of the Pure besieging the
City from the east.

### [Shadowclaws](Shadowclaws "wikilink")

The player's pack.

  - [Aleksandr](Aleksandr "wikilink")
  - [Angus](Angus "wikilink")
  - [Edouard](Edouard "wikilink")
  - [Grigor](Grigor "wikilink")
  - [Grigori](Grigori "wikilink")



## Friends and Family

Despite their savage nature, the pack has some friends among the human
population.

### [Eristoffs](Eristoffs "wikilink")

A family of Wolfblooded living in the pack's territory. Formerly used by
the Ivory Claws for breeding Pure.

  - [Alena Eristoff](Alena_Eristoff "wikilink"), girlfriend of Edouard

### Friends

A rare thing for a werewolf, some of the pack count humans as true
friends -- or more.

  - [Ivana Njatiskova](Ivana "wikilink"), a friend of Aleksandr
  - [Nadja Ivanetsch](Nadja_Ivanetsch "wikilink"), Angus' girlfriend
  - [Lana Yakisovna](Lana_Yakisovna "wikilink"), owner of [Café
    Alexanderplatz](Café_Alexanderplatz "wikilink") who harbours a crush
    on Grigor

### Work Associates

  - [Boris Koshonin](Boris_Koshonin "wikilink"), trainee of Grigor
  - [Vladimir Wecek](Vladimir_Wecek "wikilink"), mafia boss of Grigor
  - [Nievo Ashkov](Nievo_Ashkov "wikilink"), head of [Admiralteyski
    Police Department](Admiralteyski_Police_Department "wikilink") West
    and friend of Angus

## Other

Other characters the players have come into contact with.

  - [Dorofey Evgenikov](Dorofey_Evgenikov "wikilink"), patriarch of
    Petersburg
  - [Eris Bobrov](Eris_Bobrov "wikilink"), head of Admiralteyski Police
    Department East
  - [Josuv Stanov](Josuv_Stanov "wikilink"), strange kid
  - [Miika Kovalov](Miika_Kovalov "wikilink"), business magnate involved
    with [Neighbours for
    Neighbours](Neighbours_for_Neighbours "wikilink") and owner of
    [Admiralteyski Wochenblatt](Admiralteyski_Wochenblatt "wikilink")
