= Other packs

== Schatten der Zaren

The most prominent pack, centre of the alliance. "Schatten der Zaren" is a pack of werewolves living to the north of the
[Shadowclaws](Shadowclaws "wikilink"). Their territory is centred on the
[Peter and Paul
fortress.](http://en.wikipedia.org/wiki/Peter_and_Paul_fortress) Some
members of the pack are among the oldest werewolves in the city. The
pack is also the centre of the loose [alliance](alliance "wikilink") of
werewolves in St. Petersburg, as the 'High Judge' is their alpha.

"Schatten der Zaren" claims the largest Forsaken territory in the City,
extending a good part to the north and west of their stronghold. As a
blessed pack, with many members of high renown rank, and due to their
leader being High Judge, they are somewhat the "alpha pack of packs",
though they never make their leading role explicit so as not to stir up
trouble. They keep to themselves, but are willing to offer advice if
sought out on proper terms.

They often used to function as mentors for the young werewolves of the
Shadowclaws, but this has largely ceased since the Shadowclaws have
started expanding their territory and showing that they can stand on
their own feet (and claws).

The [totem](Window-to-the-West "wikilink") of "Schatten der Zaren" is
rumoured to be an old spirit of learning, though little is known about
it. The pack is highly protetive of their totem and its identity.

  - [Boris Negarov](Boris_Negarov "wikilink")
  - [Masha Rivina](Masha_Rivina "wikilink")
  - [Victor Flammendes-Schwert](Victor_Flammendes-Schwert "wikilink")
  - [Yelena Petrova](Yelena_Petrova "wikilink")
  - [Yossif Kradow](Yossif_Kradow "wikilink")

== Litanei der Straßen

A secluded pack, mostly minding their own business. They honour the
alliance but don't expect it to work.

A pack of werewolves who claim their territory to the north of the
Shadowclaws. Part of the [alliance](alliance "wikilink") of werewolves
in central St. Petersburg.

"Litanei der Straßen" is probably a more typical pack of werewolves.
They largely mind their own business, resent any interference by
outsiders and protect their territory fiercely. They have a certain
esoteric touch, and it is not known what their pack totem is. In fact
little is known about the pack beside its members and its very
territorial nature - except that they keep their territory clean and
that it is supposedly very unhealthy to enter it unannounced.

"Litanei der Straßen" has had little dealings with the
[Shadowclaws](Shadowclaws "wikilink"), partially because of their
reclusiveness, but also because their territories do not border. Only
Yelena and [Grigor](Grigor "wikilink") have met at times, due to their
common [lodge](Bear_Hunters "wikilink") - the
[Enlightened](Enlightened "wikilink") members of the pack regularly
attend the (rare) meetings of the lodge, but neither had much talk with
[Angus](Angus "wikilink") outside of
that.

  - [Dima Kochegarov](Dima_Kochegarov "wikilink")
  - [Nastya Aleksandrovna](Nastya_Aleksandrovna "wikilink")
  - [Vanya Sokolow](Vanya_Sokolow "wikilink")
  - [Yelena Dimitrovna](Yelena_Dimitrovna "wikilink")

  A pack of werewolves who claim their territory to the north of the
  Shadowclaws. Part of the [alliance](alliance "wikilink") of werewolves
  in central St. Petersburg.

  "Litanei der Straßen" is probably a more typical pack of werewolves.
  They largely mind their own business, resent any interference by
  outsiders and protect their territory fiercely. They have a certain
  esoteric touch, and it is not known what their pack totem is. In fact
  little is known about the pack beside its members and its very
  territorial nature - except that they keep their territory clean and
  that it is supposedly very unhealthy to enter it unannounced.

  "Litanei der Straßen" has had little dealings with the
  [Shadowclaws](Shadowclaws "wikilink"), partially because of their
  reclusiveness, but also because their territories do not border. Only
  Yelena and [Grigor](Grigor "wikilink") have met at times, due to their
  common [lodge](Bear_Hunters "wikilink") - the
  [Enlightened](Enlightened "wikilink") members of the pack regularly
  attend the (rare) meetings of the lodge, but neither had much talk with
  [Angus](Angus "wikilink") outside of
  that.

  |                                                                              |
  | :--------------------------------------------------------------------------: |
  |                               Current members:                               |
  |                                     Name                                     |
  |         [Vanya "Stählernes Wort" Sokolov](Vanya_Sokolow "wikilink")          |
  |       [Dima "Lied der Steine" Kochegarov](Dima_Kochegarov "wikilink")        |
  |    [Yelena "Melodie des Eisens" Dimitrovna](Yelena_Dimitrovna "wikilink")    |
  | [Nastya "Klang des Asphalts" Aleksandrovna](Nastya_Aleksandrovna "wikilink") |

== Glasfelle

An unconventional pack, consisting mostly of Iron Masters. They have a
very modern approach to life as a werewolf.

'Glasfelle' is a pack of werewolves living to the east of the
[Shadowclaws](Shadowclaws "wikilink"). They are also part of the
[alliance](alliance "wikilink"). This pack is the most 'friendly' of the
neighbours the Shadowclaws have, and especially their Iron Masters
maintain good ties with the players. Shuro has also been of help at
times, though he usually is not very forthcoming with advice, preferring
for the Shadowclaws to solve problems themselves.

The 'Glasfelle' are dominated by Iron Master ideology: They take a very
modern approach to maintaining a territory. Since two of their three
members are also in the [Lodge of Shepherds](Shepherds "wikilink"), they
have very good contact with the humans in their territory. Andrei is the
alpha of the pack (and the leader of the shepherds), though it seems
that most decisions are made by the member first encountering them and
then accepted by the pack.

Other packs watch the modern approach of the Glasfelle with disapproval,
but it appears to be working well. Their territory matches that of most
other packs in size - yet there are only three of them. Shuro seems to
do most of the fighting, and the spirits tell many tales about his
legendary skills in combat. It is noteworthy that no werewolves outside
the pack have seen him fight yet, though.

The pack's totem, called "Ubuntu", is a spirit of community. It helps
the two Shepherds understand the humans in their territory even better,
and seems to enable the pack to communicate over longer
distances.

  - [Andrei Wind-in-den-Straßen](Andrei_Wind-in-den-Straßen "wikilink")
  - [Shuro Koshonin](Shuro_Koshonin "wikilink")
  - [Vanka Iosiforna](Vanka_Iosiforna "wikilink")


== Crimson Tears

Neighbours of the players', the two packs have often clashed. The pack
changed a lot [recently](Battle_against_Rote_Wut "wikilink").

The Crimson Tears claim the former territory of [Rote
Wut](Rote_Wut "wikilink") to the south of the
[Shadowclaws](Shadowclaws "wikilink"). They were founded by [Die
Amazone](Die_Amazone "wikilink"), the last member of the Rote Wut. They
favour a different approach though: Where Rote Wut was known for its
brutality and rejection of the [alliance](alliance "wikilink"), the
Crimson Tears are a part of it and seem to be more open to dialogue.

The Shadowclaws have a favour remaining from [die
Amazone](die_Amazone "wikilink") for letting the pack use their locus.
They also helped out in a fight once, so relations seem to be quite
good. In a [recent](Breeding_Grounds "wikilink") attack by the Pure, die
Amazone was killed. Speaks-for-the-dead has taken the favour she owed
the Shadowclaws.

Since then, Boneblade has taken the Role of Alpha, and the pack has
again taken a more rejective stance towards the
[alliance](alliance "wikilink"), not showing up on any meetings except
for the [obituary](In_memory_of_Amazone "wikilink") of its former alpha.
Still, they have not formally declared that they leave the alliance. The
pack's leadership seems to rest mostly on Sergei and Arja, and both are
not very open for dialogue with werewolves outside the pack. The Crimson
Tears have made it clear they will kill trespassers, but unlike Rote Wut
have also stated they will stick to their territory - and they seem to
have observed this.

The totem of the [Crimson Tears](Crimson_Tears "wikilink") is said to be
the spirit of a certain building in their territory, where the pack
regularly meets. Rumour says its a bar (with illegal fights in the
basement), but this is not confirmed and so far noone wanted to draw
their anger by investigating matters of the pack.

  - [Arja Haajanen](Arja_Haajanen "wikilink")
  - [Ilya Eristoff](Ilya_Eristoff "wikilink")


  |                                                                 |
  | :-------------------------------------------------------------: |
  |                        Current members:                         |
  |                              Name                               |
  |            [Ilya Eristoff](Ilya_Eristoff "wikilink")            |
  | [Arja "Speaks-for-the-dead" Haajanen](Arja_Haajanen "wikilink") |

  |                                                                 |
  | :-------------------------------------------------------------: |
  |                         Former members:                         |
  |                              Name                               |
  | [Sergei "Boneblade" Grigorovich](Sergei_Grigorovich "wikilink") |
  |           [Taras Mihailov](Taras_Mihailov "wikilink")           |
  |              [Die Amazone](Die_Amazone "wikilink")              |

== Rote Wut

The pack 'Rote Wut' was the southern neighbour of the
[Shadowclaws](Shadowclaws "wikilink"). The packs [recently
clashed](Battle_against_Rote_Wut "wikilink") over territorial issues and
the fate of [Edouard](Edouard_Lambert "wikilink").

Three of the four former Members of 'Rote Wut' perished in the conflict,
and the last survivour founded a new pack, [Crimson
Tears](Crimson_Tears "wikilink").

Only '[Die Amazone](Die_Amazone "wikilink")', a Ghost Wolf Cahalith,
survived the fight - though she was half the reason it started. Having
visions of utter destruction wrought upon the werewolves of St.
Petersbourgh by the advent of [Edouard](Edouard_Lambert "wikilink"), her
pack set out to destroy him, and the pack that always aided him in the
visions - the [Shadowclaws](Shadowclaws "wikilink"). She realized the
mistake only when she realized the young werewolf was also a Cahalith,
blessed by the mother just like her. She proved essential in helping the
pack clean up the mess. Upon returning from a journey, she started
reclaiming the territory of Rote Wut with the help of the Crimson Tears.

'Klauenwind' was a Ghost Wolf Rahu, far beyond the border of sanity. Her
Harmony had dropped to very low levels, but she was still a fighting
machine able to take on the best the
[Shadowclaws](Shadowclaws "wikilink") had to offer. When the fighting
intensified, she finally lost her grip on sanity completely, and remains
missing as of now.

Sergey 'Stahlknochen' Ivanovich, the leader of the pack, was killed in a
border fight with [Grigor](Grigor "wikilink"), who unwisely took his
head home as a trophy, thereby starting an open war.

The last member of 'Rote Wut' was Flammenfell, a Pure spy, only being
able to pass along 'Rote Wut' because the pack had lost too much Harmony
to see him for what he was. A servant of Rabid Wolf, he had infected the
dreams of the packs Cahalith, in order to start a war among the
Forsaken, a war whose sole winner would be the pure surrounding the
city, waiting for their chance to strike.


== Unbound

A very rare thing for werewolves, there are still some who do not bind
themselves by pack and territory, instead choosing to wander, spending
their lives travelling. Most of these meet a quick end at the claws of a
more territorially inclined pack, but there are some who have the wits,
resources or usefulness to survive.

  - [Smauri "Forgesoul"
    Ivarrson](Smauri_"Forgesoul"_Ivarrson "wikilink"), although it seems
    he has finally settled down now
  - [Yorek "Howl-from-beyond"](Yorek_"Howl-from-beyond" "wikilink"),
    grandfather of Nadja, relieved from a terrible burden by the pack
  - [Boneblade](Sergei_Grigorovich "wikilink"), former member of Crimson
    Tears, left after a public disupte with Arja; currently it is not
    known where he is
  - Klauenwind, a former Rahu of [Rote Wut](Rote_Wut "wikilink"), lost
    in the Hisil...

== Other

Werewolves from other packs that live far away from Petersburg not to be
important as a whole.

  - [André Fazegas](André_Fazegas "wikilink"), a werewolf from Spain
    from the lodge of [Lightning](Lightning "wikilink")

== Pure

There are few Pure that the players know by name - most of the fighting
with the Pure occurs to the east of their territory, and usually they
only meet them in battle.

  - [Whitefang](Whitefang "wikilink")

== Shadowcall

An ancient fetish in the form of a battle horn. It is rumoured that the
power of the horn alone can swing a battle. The horn was carried by a
[Bear Hunter](Bear_Hunters "wikilink") hero from legend, whose name has
fallen to the mists of time. It recently made an appearance in the
dreams of the Forsaken in Petersburg, though no one seemed to have been
able to pick up its trail ...
