= Other humans

This is an overview of all important Characters in the Saga. Note that
only inhabitants of the physical world are listed here. For the strange
inhabitants of the Hisil, see [Spirits](Spirits "wikilink").

## Werewolves

There is an [alliance](alliance "wikilink") of Forsaken in the city,
trying to keep internal quarrel to a minimum. It's a very loose society,
mostly held together by the constant threat of the Pure besieging the
City from the east.

### [Shadowclaws](Shadowclaws "wikilink")

The player's pack.

  - [Aleksandr](Aleksandr "wikilink")
  - [Angus](Angus "wikilink")
  - [Edouard](Edouard "wikilink")
  - [Grigor](Grigor "wikilink")
  - [Grigori](Grigori "wikilink")



## Friends and Family

Despite their savage nature, the pack has some friends among the human
population.

### [Eristoffs](Eristoffs "wikilink")

A family of Wolfblooded living in the pack's territory. Formerly used by
the Ivory Claws for breeding Pure.

  - [Alena Eristoff](Alena_Eristoff "wikilink"), girlfriend of Edouard

### Friends

A rare thing for a werewolf, some of the pack count humans as true
friends -- or more.

  - [Ivana Njatiskova](Ivana "wikilink"), a friend of Aleksandr
  - [Nadja Ivanetsch](Nadja_Ivanetsch "wikilink"), Angus' girlfriend
  - [Lana Yakisovna](Lana_Yakisovna "wikilink"), owner of [Café
    Alexanderplatz](Café_Alexanderplatz "wikilink") who harbours a crush
    on Grigor

### Work Associates

  - [Boris Koshonin](Boris_Koshonin "wikilink"), trainee of Grigor
  - [Vladimir Wecek](Vladimir_Wecek "wikilink"), mafia boss of Grigor
  - [Nievo Ashkov](Nievo_Ashkov "wikilink"), head of [Admiralteyski
    Police Department](Admiralteyski_Police_Department "wikilink") West
    and friend of Angus

## Other

Other characters the players have come into contact with.

  - [Dorofey Evgenikov](Dorofey_Evgenikov "wikilink"), patriarch of
    Petersburg
  - [Eris Bobrov](Eris_Bobrov "wikilink"), head of Admiralteyski Police
    Department East
  - [Josuv Stanov](Josuv_Stanov "wikilink"), strange kid
  - [Miika Kovalov](Miika_Kovalov "wikilink"), business magnate involved
    with [Neighbours for
    Neighbours](Neighbours_for_Neighbours "wikilink") and owner of
    [Admiralteyski Wochenblatt](Admiralteyski_Wochenblatt "wikilink")

== Eristoffs

The Eristoffs are an old family of Wolfblooded in
[Petersburg](Petersburg "wikilink"). Their origin is not currently
known, but they seem to have served the Ivory Claws as breeding
material, producing Pure with a 'clean' heritage. The family was very
strictly organised and quite loyal to the Pure, if only out of fear of
retaliation. It was known in the area that one shouldn't ask too many
questions about them - several people had disappeared.

Apparently, when Petersburg was
[conquered](The_Legend_of_the_Lodge_of_Enlightened "wikilink") by the
Forsaken, the Pure told the family to keep its heads down, as they would
be back soon. Amazingly, the threat of the Pure returning (and, perhaps,
the advantages of a strictly-run family business) where enough to keep
the family a secret for almost a decade.

When the [Shadowclaws](Shadowclaws "wikilink")
[recently](Breeding_Grounds "wikilink") stumbled upon the Eristoffs, the
Ivory Claws were alarmed by the threat to the 'pure blood' of the
family, and attacked. The attack was beaten back with losses on both
[sides](Die_Amazone "wikilink"), though the Pure managed to abduct three
of five branches of the family.

They then settled on destroying the rest, leaking all information about
the business and its illegal practices to the police. This lead to the
arrest of Ioann, a family head. With the help of
[Edouard](Edouard "wikilink"), he managed to convince the court that he
alone was responsible, avoiding further arrests in the family.

During the first change of [Ilya Eristoff](Ilya_Eristoff "wikilink"),
the pack finally managed to convince Ilpati, the last remaining head,
that the Ivory Claws where no longer in power, and that the so-called
'traitors' were actually more benevolent. It has to be seen how the fate
of the family will develop in the future.

|                                                     |
| :-------------------------------------------------: |
| A list of known familiy members of some importance: |
|                        Name                         |
|          [Ilya](Ilya_Eristoff "wikilink")           |
|         [Alena](Alena_Eristoff "wikilink")          |
|          [Whitefang](Whitefang "wikilink")          |
|                        Ioann                        |
|                       Ilpati                        |
