= The Pack: *Shadowclaws*

Pack Name: **Shadowclaws**

Pack Totem: [Wissendes Auge der
Nacht](Wissendes_Auge_der_Nacht "wikilink"), a stray cat spirit

|                                                  |
| :----------------------------------------------: |
|                 Current members:                 |
|                    Character                     |
|    [Angus Swims-under-Ice](Angus "wikilink")     |
|      [Grigor Bears Bane](Grigor "wikilink")      |
| [Aleksandr Talks-to-Trees](Aleksandr "wikilink") |
|      [Edouard](Edouard_Lambert "wikilink")       |
|    [Grigori Open-Spaces](Grigori "wikilink")     |


== Members

== Alexandr _Talks-to-Trees_

include::player_characters/Aleksandr.adoc[]

== Angus _Swims-under-Ice_

include::player_characters/Angus.adoc[]

== Edouard

include::player_characters/Edouard.adoc[]

== Grigor _Bear's-Bane_

include::player_characters/Grigor.adoc[]

== Grigori _Open-Spaces_

include::player_characters/Grigori.adoc[]


== Resources

Here is a list of [equipment](equipment "wikilink") currently available
to the pack. Most of the pack hold (more or less regular) jobs that
provide for their needs. Only Edouard has income far beyond this, being
able to provide substantial funds for the packs projects.

The pack has a number of useful contacts entertained by some of its
members. They provide an insight into the ongoings in the city
administration, criminal activities and business interests, as well as
making it (relatively) easy for the pack to aquire more exotic chemicals
and weapons.


== Relations

The pack is not well known as an entity in general, which is how the
werewolves like it. After all, they don't want to draw to much
attention. Most in the district have heard of the 'Shadowclaws' gang,
and there is rumour that they are actually out to do good, even if it
often does not appear so. Noone could name a member, though.

Naturally, the duty of werewolves often brings them into conflict with
police (a dead ridden looks just like any other dead person). This has
escalated once, but the pack managed to shift the blame on a criminal
organisation. Since the head of police is good friends with Angus, the
pack mostly manages to avoid trouble in this direction.

(other mundanes and spirits still missing)

== Equipment

The pack is not very wealthy -- or at least wasn't until
[Edouard](Edouard_Lambert "wikilink")'s arrival -- but has accumulated a
small amount of stuff. [Grigor](Grigor "wikilink") and
[Aleksandr](Aleksandr "wikilink") both have shady contacts where they
are able to source some weapons and technical equipment. Thanks to
[Angus](Angus "wikilink")' job, the pack also has access to some
computers, light machinery, chemicals, and one motor boat.

## Military Equipment

  - 3 SMPs (2 of which recently gained)
  - 1 shotgun (1 was recently lost)
  - heavy pistol (Grigor)
  - flashbangs
  - smoke grenades
  - night goggles
  - radio equipment

## Other Equipment

  - self-caught dried fish (Angus)

## Vehicles

  - The pack's communal vehicle is a VW Sprinter: Durability 3, Size 17,
    Structure 20, Acceleration 7, Speed 73/132, Handling -1. This is
    their second Van, replacing the first one that died heroically
    during a [firefight](The_fate_of_The_Bleeding_Stone "wikilink").
  - Grigor's motorbike (Yamaha): Durability 2, Size 7, Structure 9,
    Acceleration 30, Speed 105/200, Handling 5

== OOC Rumours

Some Uratha whisper stories about the pack's strange initiation rite.
Although the truth of these stories is a bit unclear, it is said that
the real initiation is complete when the new member has shown its
allegiance toward the pack in body and spirit, meaning the initiate has
to lose most of her health and must have only a minimum of essence left
in order to be considered a true pack mate.
