=== Background

**Name:** Aleksandr-Wjatscheslav Rudenko (aka Aleksandr Berijew)

**Nationality:** Russian

**Age:** 25

**Place of Birth:** St. Petersburg

**Previous Occupation:** Information scientist / Pirate radio moderator

**Auspice:** Irraka (New Moon)

**Tribe:** Iron Masters

**Childhood**

\-- yet to be translated --

Ich wurde 1977 in St. Petersburg geboren, als zweites Kind von ??? &
???. Meine große Schwester ??? ist 4 Jahre älter, mein großer Bruder ???
9 Jahre. An meine jungen Jahre habe ich wenig Erinnerungen. Meistens hat
meine Geschwister auf mich aufgepasst, weil meine Eltern ebensoviel
arbeiteten, wie sie tranken. Manchmal haben wir Urlaub auf dem Zeltplatz
gemacht. Damals war es für mich das pure Abenteuer.

Irgendwann fing für mich die Schule an. Wir waren ausschliesslich Kinder
aus den unteren sozialen Schichten. Viele waren regelmäßig auf den
Strassen unterwegs und haben geklaut. Kindern trauen Touristen so etwas
meistens nicht zu, und so hatten sie meistens ein leichtes Spiel. Es gab
halb-organisierte Kinder- Banden, die von Älteren ”beschützt“ bzw.
ausgenommen wurden. Ich hatte anfangs nur mitgemacht, um akzeptiert zu
werden und um dazu zugehören. Doch dann merkte ich, wie lukrativ es war
und ich besserte damit mein nicht vorhandenes Taschengeld auf. Ich wurde
Mitglied in einer kleinen Gruppe, die sich auch Team-Taschendiebstahl
spezialisiert hatte. Einer quatscht Touristen an oder spritzt ihnen
irgendetwas auf die Hose, ein anderer erleichtert ihn um sein Bargeld
und ein dritter ist als Reserve dabei, um bei einer Flucht (soweit
nötig) Verwirrung zu stiften. Zwei Mal wurde ich beim Klauen erwischt.
Beim ersten Mal wusste ich noch nicht, dass man die hiesigen
”Ordnungshüter“ schmieren kann. Ich kam für sechs Monate in ein Heim.
Mich wieder in die Gruppe zu integrieren gestaltete sich als reichlich
schwierig. Die Gruppe hatte sich verändert, es waren Neue dabei, die
Hierarchiestrukturen hatten sich geändert. Meine neue Position war dann
etwas abseits als ”Ausbilder“ für Neulinge. Beim zweiten Mal (ein
Lehr-Diebstahl) hatte mich ein idealistisches Greenhorn erwischt, den
ich zwar nicht bestechen aber immerhin davon überzeugen konnte, mich
laufen zu lassen. Ich hatte ihm was vorgeheult, von wegen Leben im
Eimer, Zukunft verpfuscht, werde es nie wieder tun, etc. Er hat es mir
tatsächlich abgenommen. Ich weiß bis heute nicht, warum.

Meine Laufbahn als Taschendieb war hiermit zu Ende, wer zwei Mal
erwischt wird, hat es versaut. Ich wurde aus der Gruppe rausgeworfen. Zu
einigen von damals habe ich allerdings immer noch Kontakt. Nach meinem
Aufenthalt im Heim musste ich die Schule wechseln. In dieser Schule gab
es immerhin kein all zu kriminelles Umfeld, und ich ging auch regelmäßig
hin. Angespornt von Eltern und Geschwistern versuchte ich sogar gut
mitzuarbeiten. Nicht um aus meinem bis jetzt verkorksten Leben etwas
vernünftiges zu machen, sondern um zu verhindern, dass ich irgendwann
wieder in ein Heim muss. 1987 (ich war 10), hat mein Bruder eine Polin
geheiratet und ist zu ihr gezogen. Kurz danach ist unsere Wohnung
ausgebrannt. Mein Vater ist im Vollrausch mit einer brennenden Zigarette
in der Hand eingeschlafen. Es ist keiner zu Schaden gekommen, aber wir
haben viele Habseligkeiten verloren und mussten in eine noch kleinere
Sozialwohnung umziehen. Seit dem ist der große Streit ausgebrochen.
Meine Schwester hat meine Eltern angebrüllt, sie seien Säufer, Versager
und was-weiß-ich-noch. Über mehrere Jahre haben sich meine Schwester und
meine Eltern gegenseitig das Leben zu Hölle gemacht. Irgendwann hat mein
Vater angefangen, sie derart zu verprügeln, dass sie in ein Krankenhaus
musste. Als ich 13 war, ist meine Schwester dann weggelaufen. Ich
wusste, dass sie weg wollte, hätte aber nicht gedacht, dass sie es
tatsächlich tut. Ich hatte nicht mehr all zu viel mit ihr zu tun,
dennoch hat es mich belastet, dass sie verschwunden war. Aber ich habe
sie für ihren Mut beneidet, ein neues Leben zu beginnen.

**Youth**

Ich wechselte die Schule ein zweites Mal (diese sollte besser sein, als
die beiden vorigen). Als nun einziges übriges Kind begannen sich meine
Eltern mehr um mich zu kümmern. Außerdem haben sie auch an sich selbst
gearbeitet. Sie tranken nicht mehr ganz so viel und meine Mutter hat
sogar eine besser bezahlte Anstellung als Sekretärin bekommen. Sie hatte
vorher das 10-Finger-System an einer alten Schreibmaschine geübt. Als
sie die Stelle bekommen hatte, haben sich meine Eltern sogar einen
Computer angeschafft. Um auch zu Hause arbeiten zu können, hat der Chef
meiner Mutter uns sogar einen Internetanschluss spendiert. Meine
Gruppenzugehörigkeit habe ich dann im Internet gesucht. In der neuen
Schule habe ich keinen wirklichen Anschluss finden können. Die anderen
haben sich als etwas besseres gefühlt, für einen halber Strassenköter,
der schon als Kind im Heim war, waren sich die kleinen Damen und Herren
zu fein. Zum ersten Mal habe ich ein Gefühl dafür bekommen, wo meine
Familie in der Gesellschaft eigentlich steht. Das Bild, was die Medien
und die Schule von Russland zeichnen, unterscheidet sich ziemlich krass
von dem, was ich bis jetzt erfahren habe. Man erfährt nichts über die
Klassenunterschiede oder die Armut, keiner sagt, was ihn an diesem Land
eigentlich stört oder was man anders machen könnte. Nur im Internet
konnte man andere Meinungen aus anderen Ländern über Russland erfahren.
Ich erfuhr über die Medienzensur in Russland.

Die neue Schule begann mich anzuöden. Meine Mitschüler in ihrer eigenen
kleinen Welt gingen mir auf den Wecker und der Schulstoff interessierte
mich auch nicht. Mit 16 habe ich dann die Schule ohne Abschluss
geschmissen. Anfangs wollte ich irgend etwas mit Journalismus machen.
Ohne Abschluss habe ich allerdings keinen Ausbildungsplatz gefunden.
Schließlich habe ich -immer noch fasziniert von den Möglichkeiten des
Computers- eine Ausbildung zum Fachinformatiker bei InfoTec, einer noch
recht jungen russischen IT-Firma angefangen. In diesem Sektor gab es so
viel Bedarf, dass sie mich glücklicherweise auch ohne irgendeinen
Abschluss genommen haben.

*wtf*

My notes end here. wtf? What happened to the rest? I will need to browse
some old backups. May be it shows up. But this is a quest for another
day.

=== Stats
