=== Background

Born in Scotland, but his parents returned to the Shetland Islands when
he was four. His grandparents owned a small island near Uyea, but his
parents moved to Lerwick on the main island. Angus held a few odd jobs,
including owning a small tourist diving enterprise. After the fall of
the Soviet Union, Angus decided that a little holiday to St. Petersburg
would be a good idea -- the idea of a large town, surrounded by ice,
snow, lakes and the Baltic for diving appealed to him.

Little did he know that his holiday in St. Petersburg turned out to be a
extended stay, after his [First Change](First_Change "wikilink")
prevented him from leaving the city or returning back to the Shetland
islands -- probably for ever.

Angus tries to collect all available information on spirits in general
and on spirits in the pack's territory in particular. His calls his
collection affectionately [Angus' Spirit
Almanac](:Category:Angus'_Spirit_Almanac "wikilink").

=== Stats

**Auspice:** Ithaeur
**Tribe:** Storm Lords ([Enlightened](Enlightened "wikilink"))
**Mental Attributes:** Intelligence 3, Wits 3, Resolve 3
**Physical Attributes:** Strength 3, Dexterity 2, Stamina 3
**Social Attributes:** Presence 3, Manipulation 2, Composure 4
**Mental Skills:** Academics 1, Crafts (Boats) 2, Investigation 1,
Medicine 1, Occult (Spirits) 4, Politics (Spirits) 2, Science 1
**Physical Skills:** Athletics (Diving, Running) 3, Brawl (Urshul) 2,
Drive 1, Firearms 1, Stealth 1, Survival (Tracking) 4, Weaponry (Swords)
1
**Social Skills:** Animal Ken 1, Empathy 1, Expression 1, Intimidation
(Orders) 2, Persuasion 2, Socialize (Pubs) 1, Subterfuge 1
**Merits:** Iron Lungs 3, Iron Stomach 2, Striking Looks 2, Resources 1,
Meditative Mind 1, Allies (Enlightened) 1, Iron Stamina 1, Status (City
Hall) 1, Contacts (City Hall) 1, Allies (Police; [Nievo
Ashkov](Nievo_Ashkov "wikilink")) 1, Retainer
([Nadja](Nadja "wikilink")) 1, First Tongue 1, Russian 2
**Primal Urge:** 1
**Willpower:** 7
**Harmony:** 7
**Virtue:** Temperance
**Vice:** Pride
**Renown:** Purity 1 (3XP), Glory 1 (13 XP), Honor 2 (5 XP), Wisdom 3 (1
XP), Cunning 1 (0 XP)
**Gifts:** (1) Two-World Eyes, Call the Breeze, Death Sight, Partial
Change, Loose Tongue, Straighten; (2) Read Spirit, Luna's Dictum; (3)
Voice of Command
**Rituals:** 4; **Rites:** (1) Rite of Dedication, Shared Scent, Rite of
the Spirit Brand, Rite of Contrition; (2) Call Gaffling, Banish Spirit,
Rouse the Fetish, Rite of the Spirit Hunt; (3) Bind Spirit, Rite of
Healing, Bind Human; (4) Fetish Rite
**Fetishes:** Dog's Collar, 1 Running Rabbit
**Instincts:** Wolf's Nose
**Experience:** 10 XP
