=== Background

**Edouard Lambert** was born on November 23rd, 1971 in [La
Tuque](http://maps.google.com/maps?ie=UTF8&hl=en&ll=47.249407,-72.663574&spn=4.049341,9.162598&z=7),
Canada, as the only son of his father (a lawyer) and mother (a bookshop
owner), who died in 1997.

After finishing his education at the Universite de Montreal he assumed
several job positions, finally ending up as manager at Bombardier
Aeronautique, where he is responsible for the negotiations with other
business partners.

It is not quite clear why he and his long time girlfriend broke up about
a year ago, but his long working hours and his frequent business travels
to russia certainly didn't help to improve his relation.

After his arrival in Saint Petersburg and his [First
Change](First_Change "wikilink"), he took a while to get used to his new
life as a werewolf, but finally attained a position as CIO on the board
of [Menatep Bank](Menatep_Bank "wikilink").

## Works of Edouard as a Cahalith

  - [The Eternal Guardian](The_Eternal_Guardian "wikilink")
  - [The bleeding stone painting
    competition](The_bleeding_stone_painting_competition "wikilink")
  - [Strategic Investment](Strategic_Investment "wikilink")
  - [Investors for Neighbours](Investors_for_Neighbours "wikilink")

=== Stats

**Auspice:** [Cahalith](wod:Cahalith "wikilink")
**Tribe:** [Iron Masters](wod:Iron_Masters "wikilink")
**Lodge:** [Shepherds](Shepherds "wikilink")
**Mental Attributes:** Intelligence 2, Wits 2, Resolve 3
**Physical Attributes:** Strength 2, Dexterity 2, Stamina 2
**Social Attributes:** Presence 3, Manipulation 3, Composure 2
**Mental Skills:** Academics 2, Investigation 2, Medicine 1, Occult 1,
Politics 3, Science 1
**Physical Skills:** Athletics (running) 3, Brawl 3, Drive 1, Stealth 1,
Survival 1
**Social Skills:** Empathy (motives) 3, Expression 1, Intimidation 1,
Persuasion (bargaining) 3, Socialize 2, Subterfuge (spotting lies) 3
**Merits:** Resources 4, Status (international companies) 1, Status
(social elite St. Petersburg) 1, Contacts (local businessscene) 1,
English 1, Russian 1, First Tongue 1, Mentor ([Andrei
Wind-in-den-Straßen](Andrei_Wind-in-den-Straßen "wikilink")) 1
**Primal Urge:** 1
**Willpower:** 5
**Harmony:** 6
**Virtue:** Temperance
**Vice:** Envy
**Renown:** Purity 0 (3XP), Glory 1 (10 XP), Honor 0 (7 XP), Wisdom 1 (7
XP), Cunning 1 (4 XP)
**Giftlist:** [Gibbous Moon](wod:Gibbous_Moon_Gifts "wikilink"),
[Inspiration](wod:Inspiration_Gifts "wikilink"),
[Knowledge](wod:Knowledge_Gifts "wikilink"),
[Shaping](wod:Shaping_Gifts "wikilink"),
[Technology](wod:Technology_Gifts "wikilink"), Father Wolf, Mother
Luna
**Gifts:** \* [Rack Awareness](Rack_Awareness "wikilink") (p. 118), \*
Loose Tongue (p. 113), \* The right words (p. 125), \* Know name (p.
126), \* Sense malice (p. 122)
**Rituals:** none
**Fetishes:** none
**Instincts:** none
**Experience:** 2 XP
