=== Background

**Name:** Grigor Yaschenko

**Nationality:** Russian

**Age:** 24

**Place of Birth:** Moscow

**Previous Occupation:** Boxer / Mafia errand-boy

**Auspice:** Rahu (Full Moon)

**Tribe:** Blood Talons

**Lodge:** [Bear Hunters](Bear_Hunters "wikilink")

**Initial Appearance**

Grigor is of average height and quite lean, but keeps himself in good
physical shape, and is fairly muscular. He has black hair which he keeps
either very short or completely shaved, giving him a bit of a mean look.
Typical clothing: T-shirt and jeans, and a black leather jacket.

**Current Appearance**

Since his First Change, Grigor's increasing physical strength has become
a little harder to hide. He has already acquired a fair number of battle
scars, some of them from life-threatening wounds. Increasingly, Grigor
pays scant attention to his clothing and general appearance - he finds
that most people keep out of his way regardless. On his right arm he has
begun to tattoo a representation of each of the major foes he has
defeated, and on his (weaker) left arm, a representation of all of the
innocent victims of his rage, which are sadly at least as numerous.
Typically seen smoking a dirty-looking cigarette which emits a foul and
suspicious stench. (These "custom" cigarettes are in fact soaked in the
blood of various persons/victims, which Grigor has begun to collect.)

**Background**

Grigor was born in a poor suburb of Moscow and grew accustomed to
hardship and criminality from an early age. His mother was a prostitute
and his father died of a traffic accident (supposedly) when he was 9.
His mother was always a bit distant, and he soon dropped out of school
and fell in with a local gang, learning how to fight for himself. At the
age of 16 he started running errands for the local small-time crime
baron (part of the so-called Russian Mafia). He also joined a gym and
started to learn how to box. From hints dropped by people in the local
Mafia, he later discovered that his father had also been a member, and
he began to suspect that his death was not so accidental after all...

At the age of 19 he was arrested for possession of narcotics (a job he
was doing). He wisely did not betray his superiors, but this meant he
was sent to prison. He was released two years later, at the age of 21.
Working for the Mafia in Moscow seemed trickier with a criminal record,
and besides, he wanted to get away from there, his mum, and his past. He
was given a contact in St. Petersburg and moved there, starting with a
few simple jobs for a local crime lord. (For example, acting as a
bodyguard or driver, being sent round to threaten someone or beat them
up, that kind of thing.)

However, Grigor tried not to involve himself too heavily in crime - only
doing the minimum necessary to make ends meet. (He didn't want to end up
like his father.) His real ambition was boxing, and to become a
professional boxer. He was pretty good, and in a couple of years he had
won a half-dozen amateur middleweight fights, and was on the threshold
of becoming a pro. The local boss had supported him up to this point...
He only needed to win one more easy fight, before he would get a shot at
fighting a big name. This was when the boss ordered him to "take a
fall." The idea is to deliberately and unexpectedly lose against a
weaker opponent with long odds - and for the Mafia to make a load of
money by betting correctly on the fight. Grigor strongly wanted to
disobey his superiors, but it would have been suicide - so he gritted
his teeth and took the fall, and with it his dreams of professional
boxing were more or less over, for which he'll never forgive the boss...

**Grigor as a Werewolf**

From the beginning, Grigor's role in the pack was clear. At least at
that time, he was the only one who could fight worth a damn.
Unfortunately for the pack, however, its best fighter was also its most
prone to fury. At least in the early days, Grigor would invariably "lose
it" at some point in the battle, not resting until anyone or anything -
friend or foe - had been torn apart. Needless to say, this caused some
considerable unrest, both among the pack and in the spirit world. When
Grigor enters Death Rage, he is not so easy to stop\! One time, after
going off on a bender in the spirit world, Grigor very nearly didn't
come back alive.

Grigor quickly worked to establish the pack's authority in their
territory, through the straightfoward scheme of annihilating any rival
gangs. Unfortunately, as usual, he was a little too overenthusiastic and
hot-headed... Rumours still persist of a prolific and perverted mass
murderer in the local area, and both the police and the mafia are keen
to see this menace removed.

Grigor has struggled to get his tendency to rage under control,
successfully at times. But he is still liable to go off at any time\!

Grigor currently works for the local mafia under the direction of
[Vladimir Wecek](Vladimir_Wecek "wikilink"). He also teaches a course
entitled "Self-Confidence through Self-Defense" at the local sports
club, which is popular among the disaffected youth.

High point: Defeating the [Great Slimy One](Great_Slimy_One "wikilink")
in one-on-one combat.

Low point: Slaying the werewolf Stahlknochen of the [Rote
Wut](Rote_Wut "wikilink") to the south, and wisely taking his head home
as a trophy. Diplomacy was never his strong suit.

See also [Grigor's contrition](Grigor's_contrition "wikilink"), [The
hunt at Autumn Equinox](The_hunt_at_Autumn_Equinox "wikilink"), [The
First Job](The_First_Job "wikilink"),
[Repercussions](Repercussions "wikilink"),
[Infiltration](Infiltration "wikilink"), [A Crash
Course](A_Crash_Course "wikilink"), [Sniffing
Around](Sniffing_Around "wikilink").

=== Stats

**Mental Attributes:** Intelligence 1, Wits 4, Resolve 2
**Physical Attributes:** Strength 4, Dexterity 2, Stamina 3
**Social Attributes:** Presence 2, Manipulation 2, Composure 3
**Mental Skills:** Crafts 1, Investigation 2, Medicine 1, Occult 1
**Physical Skills:** Athletics 2, Brawl (Boxing, Urshul) 4, Drive
(Motorbike) 1, Firearms (Pistol) 2, Larceny 1, Stealth 1, Survival 1,
Weaponry (Improvised Weapons) 1
**Social Skills:** Empathy 1, Expression 1, Intimidation (Growling) 2,
Persuasion 1, Socialize 1, Streetwise 3, Subterfuge 1
**Merits:** Totem 4, Fighting Style - Boxing: Body Blow 1, Duck and
Weave 2, Combination Blows 3, Brawling Dodge 1, Status (Mafia) 1, Allies
(Mafia) 1, Contacts (Youth) 1, Mentor ([Yelena
Dimitrovna](Yelena_Dimitrovna "wikilink")) 1, Resources 1
**Primal Urge:** 4
**Willpower:** 5
**Harmony:** 4
**Virtue:** Justice
**Vice:** Wrath
**Renown:** Purity 2 (17 XP), Glory 3 (0 XP), Honor 1 (6 XP), Wisdom 0
(1 XP), Cunning 0 (5 XP)
**Gifts:** (1) Clarity, Warning Growl, Crushing Blow, The Right Words,
Partial Change; (2) Mighty Bound, Attunement, Father Wolf's Speed; (3)
True Leader
**Rituals:** 1; **Rites:** (1) Rite of Contrition
**Instincts:** Predator, Stalker, (two more)
**Experience Points:** 21
